In [3]:
# ============================================================
# VERIFICACIÓN DE PÉRDIDA DE HILOS / ISSUES
# ============================================================

import pandas as pd
import numpy as np

# ------------------------------------------------------------
# 1. CARGAR DATASET ORIGINAL
# ------------------------------------------------------------
# Usa aquí el archivo ANTES de eliminar ruido.
# Debe tener issue_number y comment_body_clean_final o comment_body_raw.

original_file = "Dataset_integration_semantico_topk_enriched_final.xlsx"

df_original = pd.read_excel(original_file)

print("Dataset original cargado:")
print(df_original.shape)

print("\nColumnas del dataset original:")
print(df_original.columns.tolist())

Dataset original cargado:
(3761, 59)

Columnas del dataset original:
['repo', 'issue_number', 'comment_id', 'comment_author', 'comment_created_at', 'comment_body_raw', 'comment_body_clean_final', 'true_code', 'evaluable', 'match', 'final_cause_code', 'final_cause_for_analysis', 'predicted_code', 'predicted_label', 'Code_cause_llm', 'predicted_label_llm', 'Confidence_llm', 'Confidence', 'Requires_revision', 'State_prediction', 'Priority_rule_applied', 'rule_changed_llm', 'macro_cause_clean', 'comment_length', 'primary_microcause_id', 'primary_microcause_name', 'primary_microcause_type', 'primary_similarity_score', 'top_microcause_ids', 'top_microcause_names', 'top_microcause_types', 'top_microcause_scores', 'top_microcause_count', 'classification_status_topk', 'debug_comment_text', 'debug_best_comment_score', 'debug_best_macro_score', 'debug_best_lex_bonus', 'debug_second_score', 'debug_score_gap', 'microcause_1_id', 'microcause_1_name', 'microcause_1_type', 'microcause_1_score', 'microcause_2_id', 'microcause_2_name', 'microcause_2_type', 'microcause_2_score', 'microcause_3_id', 'microcause_3_name', 'microcause_3_type', 'microcause_3_score', 'preventive_strategies', 'effects', 'corrective_strategies', 'indicators', 'metrics', 'risks', 'community_smells']

In [5]:
# ------------------------------------------------------------
# 2. USAR DATASET OPERACIONAL ACTUAL
# ------------------------------------------------------------
# Si ya existe df_operational_28 en memoria, úsalo.
# Si no existe, carga el archivo exportado.

# Opción A: si ya está en memoria
#df_operational = df_operational_28.copy()

# Opción B: si no está en memoria, descomenta:
df_operational = pd.read_excel("Dataset_integration_semantico_topk_enriched_final.xlsx")

print("Dataset operacional:")
print(df_operational.shape)

Dataset operacional:
(3761, 59)

In [ ]:
# ============================================================
# VERIFICACIÓN DE PÉRDIDA DE HILOS / ISSUES
# ============================================================

import pandas as pd
import numpy as np

# ------------------------------------------------------------
# 1. CARGAR DATASET ORIGINAL
# ------------------------------------------------------------
# Usa aquí el archivo ANTES de eliminar ruido.
# Debe tener issue_number y comment_body_clean_final o comment_body_raw.

original_file = "Dataset_integration_semantico_topk_enriched_final.xlsx"

df_original = pd.read_excel(original_file)

print("Dataset original cargado:")
print(df_original.shape)

print("\nColumnas del dataset original:")
print(df_original.columns.tolist())

Dataset original cargado:
(3761, 59)

Columnas del dataset original:
['repo', 'issue_number', 'comment_id', 'comment_author', 'comment_created_at', 'comment_body_raw', 'comment_body_clean_final', 'true_code', 'evaluable', 'match', 'final_cause_code', 'final_cause_for_analysis', 'predicted_code', 'predicted_label', 'Code_cause_llm', 'predicted_label_llm', 'Confidence_llm', 'Confidence', 'Requires_revision', 'State_prediction', 'Priority_rule_applied', 'rule_changed_llm', 'macro_cause_clean', 'comment_length', 'primary_microcause_id', 'primary_microcause_name', 'primary_microcause_type', 'primary_similarity_score', 'top_microcause_ids', 'top_microcause_names', 'top_microcause_types', 'top_microcause_scores', 'top_microcause_count', 'classification_status_topk', 'debug_comment_text', 'debug_best_comment_score', 'debug_best_macro_score', 'debug_best_lex_bonus', 'debug_second_score', 'debug_score_gap', 'microcause_1_id', 'microcause_1_name', 'microcause_1_type', 'microcause_1_score', 'microcause_2_id', 'microcause_2_name', 'microcause_2_type', 'microcause_2_score', 'microcause_3_id', 'microcause_3_name', 'microcause_3_type', 'microcause_3_score', 'preventive_strategies', 'effects', 'corrective_strategies', 'indicators', 'metrics', 'risks', 'community_smells']

In [6]:
# ------------------------------------------------------------
# 3. VALIDAR QUE AMBOS TIENEN issue_number
# ------------------------------------------------------------

print("issue_number en original:", "issue_number" in df_original.columns)
print("issue_number en operacional:", "issue_number" in df_operational.columns)

issue_number en original: True
issue_number en operacional: True

In [7]:
# ------------------------------------------------------------
# 4. COMPARAR ISSUES ÚNICOS
# ------------------------------------------------------------

original_issues = set(df_original["issue_number"].dropna().unique())
operational_issues = set(df_operational["issue_number"].dropna().unique())

lost_issues = original_issues - operational_issues
new_issues = operational_issues - original_issues

print("==============================================")
print("COMPARACIÓN DE ISSUES")
print("==============================================")
print("Issues en original:", len(original_issues))
print("Issues en operacional:", len(operational_issues))
print("Issues perdidos:", len(lost_issues))
print("Issues nuevos inesperados:", len(new_issues))

==============================================
COMPARACIÓN DE ISSUES
==============================================
Issues en original: 265
Issues en operacional: 265
Issues perdidos: 0
Issues nuevos inesperados: 0

In [8]:
print(df_original.columns.tolist())

['repo', 'issue_number', 'comment_id', 'comment_author', 'comment_created_at', 'comment_body_raw', 'comment_body_clean_final', 'true_code', 'evaluable', 'match', 'final_cause_code', 'final_cause_for_analysis', 'predicted_code', 'predicted_label', 'Code_cause_llm', 'predicted_label_llm', 'Confidence_llm', 'Confidence', 'Requires_revision', 'State_prediction', 'Priority_rule_applied', 'rule_changed_llm', 'macro_cause_clean', 'comment_length', 'primary_microcause_id', 'primary_microcause_name', 'primary_microcause_type', 'primary_similarity_score', 'top_microcause_ids', 'top_microcause_names', 'top_microcause_types', 'top_microcause_scores', 'top_microcause_count', 'classification_status_topk', 'debug_comment_text', 'debug_best_comment_score', 'debug_best_macro_score', 'debug_best_lex_bonus', 'debug_second_score', 'debug_score_gap', 'microcause_1_id', 'microcause_1_name', 'microcause_1_type', 'microcause_1_score', 'microcause_2_id', 'microcause_2_name', 'microcause_2_type', 'microcause_2_score', 'microcause_3_id', 'microcause_3_name', 'microcause_3_type', 'microcause_3_score', 'preventive_strategies', 'effects', 'corrective_strategies', 'indicators', 'metrics', 'risks', 'community_smells']

In [9]:
# ------------------------------------------------------------
# 5. COMPARAR COMENTARIOS POR ISSUE
# ------------------------------------------------------------

original_counts = (
    df_original
    .groupby("issue_number")
    .size()
    .reset_index(name="original_comments")
)

operational_counts = (
    df_operational
    .groupby("issue_number")
    .size()
    .reset_index(name="operational_comments")
)

issue_loss = original_counts.merge(
    operational_counts,
    on="issue_number",
    how="left"
)

issue_loss["operational_comments"] = (
    issue_loss["operational_comments"]
    .fillna(0)
    .astype(int)
)

issue_loss["lost_comments"] = (
    issue_loss["original_comments"]
    -
    issue_loss["operational_comments"]
)

issue_loss["loss_percentage"] = (
    issue_loss["lost_comments"]
    /
    issue_loss["original_comments"]
    * 100
).round(2)

display(
    issue_loss.sort_values(
        "loss_percentage",
        ascending=False
    ).head(30)
)

,issue_number,original_comments,operational_comments,lost_comments,loss_percentage
264,291739,18,18,0,0.0
0,17660,13,13,0,0.0
1,17675,27,27,0,0.0
2,17690,11,11,0,0.0
3,17806,16,16,0,0.0
4,17809,18,18,0,0.0
5,17910,33,33,0,0.0
6,18056,41,41,0,0.0
7,18158,39,39,0,0.0
248,136095,16,16,0,0.0
247,136074,3,3,0,0.0
246,136064,6,6,0,0.0
245,136049,12,12,0,0.0
244,136028,20,20,0,0.0
243,136027,26,26,0,0.0
242,136025,18,18,0,0.0
241,136021,17,17,0,0.0
240,136014,8,8,0,0.0
239,135951,8,8,0,0.0
238,135919,15,15,0,0.0
237,135835,13,13,0,0.0
236,135829,3,3,0,0.0
235,135805,2,2,0,0.0
234,135794,17,17,0,0.0
233,135782,8,8,0,0.0
40,58750,2,2,0,0.0
39,58748,17,17,0,0.0
38,58730,28,28,0,0.0
37,58729,21,21,0,0.0
36,58693,11,11,0,0.0

In [11]:
df = pd.read_excel(
    "Dataset_integration_semantico_topk_enriched_final.xlsx"
)

print(df.shape)

print(df.columns.tolist())

(3761, 59)
['repo', 'issue_number', 'comment_id', 'comment_author', 'comment_created_at', 'comment_body_raw', 'comment_body_clean_final', 'true_code', 'evaluable', 'match', 'final_cause_code', 'final_cause_for_analysis', 'predicted_code', 'predicted_label', 'Code_cause_llm', 'predicted_label_llm', 'Confidence_llm', 'Confidence', 'Requires_revision', 'State_prediction', 'Priority_rule_applied', 'rule_changed_llm', 'macro_cause_clean', 'comment_length', 'primary_microcause_id', 'primary_microcause_name', 'primary_microcause_type', 'primary_similarity_score', 'top_microcause_ids', 'top_microcause_names', 'top_microcause_types', 'top_microcause_scores', 'top_microcause_count', 'classification_status_topk', 'debug_comment_text', 'debug_best_comment_score', 'debug_best_macro_score', 'debug_best_lex_bonus', 'debug_second_score', 'debug_score_gap', 'microcause_1_id', 'microcause_1_name', 'microcause_1_type', 'microcause_1_score', 'microcause_2_id', 'microcause_2_name', 'microcause_2_type', 'microcause_2_score', 'microcause_3_id', 'microcause_3_name', 'microcause_3_type', 'microcause_3_score', 'preventive_strategies', 'effects', 'corrective_strategies', 'indicators', 'metrics', 'risks', 'community_smells']

In [ ]:
cols = [
    "top_microcause_names",
    "top_microcause_scores",
    "community_smells",
    "risks"
]

display(df[cols].head(10))

,top_microcause_names,top_microcause_scores,community_smells,risks
0,['Lack of Interface Clarification'],[0.279686],• Socio-Technical Congruence Gap,• RSK-013_TechnicalMaintenanceRisk\n• RSK-021_...
1,"['Lack of Interface Clarification', 'System co...","[0.342248, 0.305052]",• Missing Link,• RSK-005_Documentation_Gaps_Risk
2,['Lack of Interface Clarification'],[0.293476],• Missing Link,• RSK-005_Documentation_Gaps_Risk
3,['Lack of Interface Clarification'],[0.295672],• Missing Link,• RSK-005_Documentation_Gaps_Risk
4,['Unclear or ambiguous communication'],[0.340946],• Power Distance,• RSK-002_Feedback_Delays_Risk
5,"['Delayed Communication', 'Unclear or ambiguou...","[0.301675, 0.301206]",• Power Distance,• RSK-002_Feedback_Delays_Risk
6,['System configuration constraints'],[0.307611],• Missing Link,• RSK-005_Documentation_Gaps_Risk
7,"['Lack of Interface Clarification', 'Technical...","[0.370907, 0.335503, 0.321722]",• Missing Link,• RSK-005_Documentation_Gaps_Risk
8,"['Lack of Interface Clarification', 'Technical...","[0.328871, 0.311222, 0.307275]",• Missing Link,• RSK-005_Documentation_Gaps_Risk
9,['Unclear or ambiguous communication'],[0.362004],• Missing Link\n• Power Distance,• RSK-010_MiscommunicationRisk\n• RSK-020_Misi...

In [12]:
# ============================================================
# PASO 1. FUNCIONES PARA PARSEAR LISTAS Y VIÑETAS
# ============================================================

import ast
import pandas as pd
from collections import Counter

def parse_list_cell(value):
    if pd.isna(value):
        return []
    try:
        return ast.literal_eval(str(value))
    except:
        return []

def parse_bullet_cell(value):
    if pd.isna(value):
        return []

    items = []
    for line in str(value).split("\n"):
        line = line.strip()
        line = line.replace("•", "").strip()
        if line:
            items.append(line)
    return items

In [13]:
# ============================================================
# PASO 2. PARSEAR COLUMNAS TOP-K, SMELLS Y RIESGOS
# ============================================================

df["top_microcause_names_list"] = df["top_microcause_names"].apply(parse_list_cell)
df["top_microcause_scores_list"] = df["top_microcause_scores"].apply(parse_list_cell)

df["community_smells_list"] = df["community_smells"].apply(parse_bullet_cell)
df["risks_list"] = df["risks"].apply(parse_bullet_cell)

display(df[
    [
        "issue_number",
        "top_microcause_names_list",
        "top_microcause_scores_list",
        "community_smells_list",
        "risks_list"
    ]
].head(10))

,issue_number,top_microcause_names_list,top_microcause_scores_list,community_smells_list,risks_list
0,291739,"[Compatibility Constraints, Lack of Interface ...","[0.312909, 0.306751]","[['Missing Link', 'Socio-Technical Congruence ...","[['RSK-005_Documentation_Gaps_Risk', 'RSK-013_..."
1,291739,"[Lack of Interface Clarification, System confi...","[0.375113, 0.32742, 0.319257]","[['Missing Link', 'Socio-Technical Congruence ...","[['RSK-005_Documentation_Gaps_Risk', 'RSK-013_..."
2,291739,"[Lack of Interface Clarification, Compatibilit...","[0.308349, 0.300198, 0.289076]","[['Missing Link', 'Socio-Technical Congruence ...","[['RSK-005_Documentation_Gaps_Risk', 'RSK-013_..."
3,291739,[Lack of Interface Clarification],[0.309537],[['Missing Link']],[['RSK-005_Documentation_Gaps_Risk']]
4,291739,[Unclear or ambiguous communication],[0.357613],"[['Missing Link', 'Power Distance']]","[['RSK-010_MiscommunicationRisk', 'RSK-020_Mis..."
5,291739,"[Unclear or ambiguous communication, Delayed C...","[0.317873, 0.301675]","[['Missing Link', 'Power Distance']]","[['RSK-002_Feedback_Delays_Risk', 'RSK-010_Mis..."
6,291739,"[System configuration constraints, Lack of Int...","[0.328026, 0.293908, 0.28442]","[['Missing Link', 'Socio-Technical Congruence ...","[['RSK-005_Documentation_Gaps_Risk', 'RSK-013_..."
7,291739,"[Lack of Interface Clarification, Compatibilit...","[0.375702, 0.349728, 0.329044]","[['Missing Link', 'Organizational Silo', 'Soci...","[['RSK-005_Documentation_Gaps_Risk', 'RSK-006_..."
8,291739,"[Compatibility Constraints, Lack of Interface ...","[0.389949, 0.346736, 0.307615]","[['Missing Link', 'Socio-Technical Congruence ...","[['RSK-005_Documentation_Gaps_Risk', 'RSK-013_..."
9,291739,"[Unclear or ambiguous communication, Delayed C...","[0.362004, 0.291653]","[['Missing Link', 'Power Distance']]","[['RSK-002_Feedback_Delays_Risk', 'RSK-010_Mis..."

In [14]:
# ============================================================
# PASO 3. AGREGAR MICROCAUSAS, SMELLS Y RIESGOS POR ISSUE
# ============================================================

def aggregate_issue(group):

    micro_counter = Counter()
    smell_counter = Counter()
    risk_counter = Counter()
    macro_counter = Counter()

    for _, row in group.iterrows():

        macro_counter[row["final_cause_for_analysis"]] += 1

        micro_names = row["top_microcause_names_list"]
        micro_scores = row["top_microcause_scores_list"]

        for name, score in zip(micro_names, micro_scores):
            micro_counter[name] += float(score)

        for smell in row["community_smells_list"]:
            smell_counter[smell] += 1

        for risk in row["risks_list"]:
            risk_counter[risk] += 1

    return pd.Series({
        "comment_count": len(group),
        "dominant_macrocauses": macro_counter.most_common(5),
        "dominant_microcauses": micro_counter.most_common(5),
        "dominant_community_smells": smell_counter.most_common(5),
        "dominant_risks": risk_counter.most_common(5),
        "issue_text": "\n\n".join(group["comment_body_clean_final"].astype(str))
    })

In [15]:
# ============================================================
# PASO 4. DATASET ADAPTATIVO POR ISSUE
# ============================================================

df_issue_adaptive = (
    df
    .sort_values(["issue_number", "comment_created_at"])
    .groupby("issue_number")
    .apply(aggregate_issue)
    .reset_index()
)

print("Dataset adaptativo por issue:")
print(df_issue_adaptive.shape)

display(df_issue_adaptive.head())

Dataset adaptativo por issue:
(265, 7)

/tmp/ipykernel_1394/2697747653.py:9: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(aggregate_issue)

,issue_number,comment_count,dominant_macrocauses,dominant_microcauses,dominant_community_smells,dominant_risks,issue_text
0,17660,13,"[(Coordination and workflow misalignment, 8), ...",[(Coordination misalignment for technical vali...,"[(['Missing Link', 'Organizational Silo'], 3),...","[(['RSK-012_ReworkRisk'], 4), (['RSK-005_Docum...","Hello. A GitHub user is mentioned. , thank you..."
1,17675,27,"[(Coordination and workflow misalignment, 10),...","[(Task rework due to misalignment, 1.820599999...","[(['Missing Link', 'Socio-Technical Congruence...","[(['RSK-004_Language_Miscommunication_Risk', '...","Just to rephrase, slightly...\n\nbased on the ..."
2,17690,11,"[(Coordination and workflow misalignment, 6), ...","[(Task rework due to misalignment, 1.108471), ...","[(['Missing Link', 'Power Distance'], 3), (['M...","[(['RSK-012_ReworkRisk'], 4), (['RSK-010_Misco...",_(I was torn by the first commit. It's very st...
3,17806,16,"[(Coordination and workflow misalignment, 6), ...",[(Coordination misalignment for technical vali...,"[(['Socio-Technical Congruence Gap'], 4), (['M...","[(['RSK-012_ReworkRisk'], 6), (['RSK-011_Knowl...",I will check these new instructions during the...
4,17809,18,"[(Coordination and workflow misalignment, 7), ...","[(Compatibility Constraints, 2.159039), (Task ...","[(['Missing Link', 'Socio-Technical Congruence...","[(['RSK-013_TechnicalMaintenanceRisk', 'RSK-02...",Please let me know if we can continue with thi...

In [16]:
# ============================================================
# PASO 6. MÉTRICAS ADAPTATIVAS POR ISSUE
# ============================================================

def count_items(x):
    if isinstance(x, list):
        return len(x)
    return 0

def top_frequency(x):
    if isinstance(x, list) and len(x) > 0:
        return x[0][1]
    return 0

df_issue_adaptive["macro_diversity"] = (
    df_issue_adaptive["dominant_macrocauses"]
    .apply(count_items)
)

df_issue_adaptive["micro_diversity"] = (
    df_issue_adaptive["dominant_microcauses"]
    .apply(count_items)
)

df_issue_adaptive["risk_diversity"] = (
    df_issue_adaptive["dominant_risks"]
    .apply(count_items)
)

df_issue_adaptive["smell_diversity"] = (
    df_issue_adaptive["dominant_community_smells"]
    .apply(count_items)
)

df_issue_adaptive["top_macro_frequency"] = (
    df_issue_adaptive["dominant_macrocauses"]
    .apply(top_frequency)
)

df_issue_adaptive["top_micro_score"] = (
    df_issue_adaptive["dominant_microcauses"]
    .apply(top_frequency)
)

df_issue_adaptive["top_smell_frequency"] = (
    df_issue_adaptive["dominant_community_smells"]
    .apply(top_frequency)
)

df_issue_adaptive["top_risk_frequency"] = (
    df_issue_adaptive["dominant_risks"]
    .apply(top_frequency)
)

display(df_issue_adaptive.head())

,issue_number,comment_count,dominant_macrocauses,dominant_microcauses,dominant_community_smells,dominant_risks,issue_text,macro_diversity,micro_diversity,risk_diversity,smell_diversity,top_macro_frequency,top_micro_score,top_smell_frequency,top_risk_frequency
0,17660,13,"[(Coordination and workflow misalignment, 8), ...",[(Coordination misalignment for technical vali...,"[(['Missing Link', 'Organizational Silo'], 3),...","[(['RSK-012_ReworkRisk'], 4), (['RSK-005_Docum...","Hello. A GitHub user is mentioned. , thank you...",3,5,5,5,8,1.077334,3,4
1,17675,27,"[(Coordination and workflow misalignment, 10),...","[(Task rework due to misalignment, 1.820599999...","[(['Missing Link', 'Socio-Technical Congruence...","[(['RSK-004_Language_Miscommunication_Risk', '...","Just to rephrase, slightly...\n\nbased on the ...",5,5,5,5,10,1.820600,5,3
2,17690,11,"[(Coordination and workflow misalignment, 6), ...","[(Task rework due to misalignment, 1.108471), ...","[(['Missing Link', 'Power Distance'], 3), (['M...","[(['RSK-012_ReworkRisk'], 4), (['RSK-010_Misco...",_(I was torn by the first commit. It's very st...,4,5,5,5,6,1.108471,3,4
3,17806,16,"[(Coordination and workflow misalignment, 6), ...",[(Coordination misalignment for technical vali...,"[(['Socio-Technical Congruence Gap'], 4), (['M...","[(['RSK-012_ReworkRisk'], 6), (['RSK-011_Knowl...",I will check these new instructions during the...,4,5,5,5,6,1.408837,4,6
4,17809,18,"[(Coordination and workflow misalignment, 7), ...","[(Compatibility Constraints, 2.159039), (Task ...","[(['Missing Link', 'Socio-Technical Congruence...","[(['RSK-013_TechnicalMaintenanceRisk', 'RSK-02...",Please let me know if we can continue with thi...,5,5,5,5,7,2.159039,5,4

In [17]:
from collections import Counter

macro_counter = Counter()

for macros in df_issue_adaptive["dominant_macrocauses"]:
    for macro, freq in macros:
        macro_counter[macro] += freq

macro_df = (
    pd.DataFrame(
        macro_counter.items(),
        columns=["macrocause", "frequency"]
    )
    .sort_values("frequency", ascending=False)
)

display(macro_df)

                                          macrocause  frequency
1  Technical complexity, compatibility, and syste...       1125
0             Coordination and workflow misalignment       1011
2  Communication and shared understanding breakdowns        562
3  Resource, tooling, access, and validation depe...        446
4  Organizational and procedural workflow constra...        277
5  Knowledge, documentation, and standards defici...        228
6           Collaboration and interpersonal tensions         60

In [18]:
# ============================================================
# FASE II - PASO 2. MICROCAUSAS DOMINANTES GLOBALES
# ============================================================

from collections import Counter
import pandas as pd

micro_counter = Counter()

for micros in df_issue_adaptive["dominant_microcauses"]:
    for micro, score in micros:
        micro_counter[micro] += score

micro_df = (
    pd.DataFrame(
        micro_counter.items(),
        columns=["microcause", "aggregated_score"]
    )
    .sort_values("aggregated_score", ascending=False)
)

display(micro_df.head(20))

                                           microcause  aggregated_score
3                           Compatibility Constraints        271.268228
2                     Task rework due to misalignment        184.951912
9                    System configuration constraints        182.328732
0   Coordination misalignment for technical valida...        168.266535
5                     Lack of Interface Clarification        145.431303
13                    Inefficient or inadequate tools        108.125913
1                         Restricted Information Flow         70.214149
7                  Unclear or ambiguous communication         57.016648
14           Request for Technical Validation Support         54.990012
21           Technical complexity due to dependencies         50.993791
10         Constraint due to ticket status for review         30.687420
15              Preservation of prior system behavior         28.731841
6                   Miscommunication In Task Handover         26.672571
22              Blockage due to approval requirements         23.950279
23                       Repository access limitation         21.165884
8                     Lack of technical documentation         21.088629
18                              Delayed Communication         14.173771
19                   Misinterpretation of information         12.665761
4                          Unilateral Task Assignment          9.191789
25                Lack of timely feedback or response          7.308716

In [19]:
from collections import Counter

smell_counter = Counter()

for smells in df_issue_adaptive["dominant_community_smells"]:
    for smell, freq in smells:
        smell_counter[smell] += freq

smell_df = (
    pd.DataFrame(
        smell_counter.items(),
        columns=["community_smell", "frequency"]
    )
    .sort_values("frequency", ascending=False)
)

display(smell_df)

                                      community_smell  frequency
5   ['Missing Link', 'Socio-Technical Congruence G...        433
2                  ['Socio-Technical Congruence Gap']        335
4                  ['Missing Link', 'Power Distance']        277
7                                  ['Power Distance']        257
6   ['Missing Link', 'Organizational Silo', 'Socio...        240
0             ['Missing Link', 'Organizational Silo']        195
12  ['Organizational Silo', 'Socio-Technical Congr...        184
13  ['Missing Link', 'Organizational Silo', 'Socio...        129
1                                    ['Missing Link']        120
8                 ['Knowledge Silos', 'Truck Factor']        115
10  ['Socio-Technical Congruence Gap', 'Truck Fact...        104
11          ['Organizational Silo', 'Power Distance']         98
9   ['Missing Link', 'Organizational Silo', 'Power...         96
21  ['Missing Link', 'Socio-Technical Congruence G...         51
14                   ['Missing Link', 'Truck Factor']         30
32  ['Organizational Silo', 'Power Distance', 'Sha...         22
3   ['Missing Link', 'Power Distance', 'Socio-Tech...         20
16                         ['Organizational Silence']         20
15                            ['Organizational Silo']         20
34  ['Missing Link', 'Organizational Silo', 'Power...         16
26  ['Missing Link', 'Organizational Silence', 'Po...         13
18  ['Missing Link', 'Organizational Silo', 'Prima...         12
27                 ['Power Distance', 'Prima Donnas']          8
17  ['Missing Link', 'Power Distance', 'Prima Donn...          8
23  ['Knowledge Silos', 'Missing Link', 'Organizat...          8
19                ['Prima Donnas', 'Shared Villainy']          7
25  ['Missing Link', 'Organizational Silo', 'Truck...          7
30  ['Missing Link', 'Prima Donnas', 'Socio-Techni...          6
24                                   ['Prima Donnas']          5
39  ['Missing Link', 'Power Distance', 'Prima Donn...          3
38  ['Organizational Silo', 'Socio-Technical Congr...          2
31  ['Missing Link', 'Organizational Silo', 'Power...          2
29       ['Organizational Silence', 'Power Distance']          2
28         ['Organizational Silo', 'Shared Villainy']          2
22                   ['Missing Link', 'Prima Donnas']          1
20  ['Missing Link', 'Organizational Silo', 'Power...          1
33  ['Organizational Silence', 'Power Distance', '...          1
35  ['Knowledge Silos', 'Power Distance', 'Truck F...          1
37            ['Organizational Silo', 'Truck Factor']          1
36         ['Missing Link', 'Organizational Silence']          1
40  ['Missing Link', 'Organizational Silo', 'Prima...          1
41  ['Knowledge Silos', 'Missing Link', 'Organizat...          1

In [20]:
# ============================================================
# FASE III. SOCIAL DEBT INDEX
# PASO 1. VARIABLES BASE POR ISSUE
# ============================================================

def list_len(x):
    if isinstance(x, list):
        return len(x)
    return 0

def top_value(x):
    if isinstance(x, list) and len(x) > 0:
        return x[0][1]
    return 0

df_issue_adaptive["macro_diversity"] = (
    df_issue_adaptive["dominant_macrocauses"].apply(list_len)
)

df_issue_adaptive["micro_diversity"] = (
    df_issue_adaptive["dominant_microcauses"].apply(list_len)
)

df_issue_adaptive["smell_diversity"] = (
    df_issue_adaptive["dominant_community_smells"].apply(list_len)
)

df_issue_adaptive["risk_diversity"] = (
    df_issue_adaptive["dominant_risks"].apply(list_len)
)

df_issue_adaptive["top_macro_frequency"] = (
    df_issue_adaptive["dominant_macrocauses"].apply(top_value)
)

df_issue_adaptive["top_micro_score"] = (
    df_issue_adaptive["dominant_microcauses"].apply(top_value)
)

df_issue_adaptive["top_smell_frequency"] = (
    df_issue_adaptive["dominant_community_smells"].apply(top_value)
)

df_issue_adaptive["top_risk_frequency"] = (
    df_issue_adaptive["dominant_risks"].apply(top_value)
)

display(
    df_issue_adaptive[
        [
            "issue_number",
            "comment_count",
            "macro_diversity",
            "micro_diversity",
            "smell_diversity",
            "risk_diversity",
            "top_macro_frequency",
            "top_micro_score",
            "top_smell_frequency",
            "top_risk_frequency"
        ]
    ].head(10)
)

,issue_number,comment_count,macro_diversity,micro_diversity,smell_diversity,risk_diversity,top_macro_frequency,top_micro_score,top_smell_frequency,top_risk_frequency
0,17660,13,3,5,5,5,8,1.077334,3,4
1,17675,27,5,5,5,5,10,1.820600,5,3
2,17690,11,4,5,5,5,6,1.108471,3,4
3,17806,16,4,5,5,5,6,1.408837,4,6
4,17809,18,5,5,5,5,7,2.159039,5,4
5,17910,33,5,5,5,5,12,2.654006,7,9
6,18056,41,4,5,5,5,15,4.331518,7,8
7,18158,39,5,5,5,5,13,3.708487,12,10
8,18266,42,5,5,5,5,24,5.004502,8,12
9,18361,33,5,5,5,5,11,3.607408,7,4

In [21]:
# ============================================================
# FASE III. SOCIAL DEBT INDEX
# PASO 2. NORMALIZACIÓN DE VARIABLES
# ============================================================

from sklearn.preprocessing import MinMaxScaler

sdi_features = [
    "comment_count",
    "macro_diversity",
    "micro_diversity",
    "smell_diversity",
    "risk_diversity",
    "top_macro_frequency",
    "top_micro_score",
    "top_smell_frequency",
    "top_risk_frequency"
]

scaler = MinMaxScaler()

normalized_values = scaler.fit_transform(
    df_issue_adaptive[sdi_features]
)

df_sdi_norm = pd.DataFrame(
    normalized_values,
    columns=[f"{col}_norm" for col in sdi_features]
)

df_issue_adaptive = pd.concat(
    [
        df_issue_adaptive.reset_index(drop=True),
        df_sdi_norm
    ],
    axis=1
)

display(
    df_issue_adaptive[
        ["issue_number"] + [f"{col}_norm" for col in sdi_features]
    ].head(10)
)

,issue_number,comment_count_norm,macro_diversity_norm,micro_diversity_norm,smell_diversity_norm,risk_diversity_norm,top_macro_frequency_norm,top_micro_score_norm,top_smell_frequency_norm,top_risk_frequency_norm
0,17660,0.160000,0.50,1.0,1.0,1.0,0.179487,0.069701,0.142857,0.214286
1,17675,0.346667,1.00,1.0,1.0,1.0,0.230769,0.133645,0.285714,0.142857
2,17690,0.133333,0.75,1.0,1.0,1.0,0.128205,0.072379,0.142857,0.214286
3,17806,0.200000,0.75,1.0,1.0,1.0,0.128205,0.098220,0.214286,0.357143
4,17809,0.226667,1.00,1.0,1.0,1.0,0.153846,0.162761,0.285714,0.214286
5,17910,0.426667,1.00,1.0,1.0,1.0,0.282051,0.205344,0.428571,0.571429
6,18056,0.533333,0.75,1.0,1.0,1.0,0.358974,0.349663,0.428571,0.500000
7,18158,0.506667,1.00,1.0,1.0,1.0,0.307692,0.296062,0.785714,0.642857
8,18266,0.546667,1.00,1.0,1.0,1.0,0.589744,0.407560,0.500000,0.785714
9,18361,0.426667,1.00,1.0,1.0,1.0,0.256410,0.287366,0.428571,0.214286

In [22]:
# ============================================================
# PASO 3. ESTADÍSTICAS DESCRIPTIVAS
# ============================================================

cols = [
    "comment_count",
    "macro_diversity",
    "micro_diversity",
    "smell_diversity",
    "risk_diversity",
    "top_macro_frequency",
    "top_micro_score",
    "top_smell_frequency",
    "top_risk_frequency"
]

display(
    df_issue_adaptive[cols]
    .describe()
    .round(3)
)

,comment_count,macro_diversity,micro_diversity,smell_diversity,risk_diversity,top_macro_frequency,top_micro_score,top_smell_frequency,top_risk_frequency
count,265.000,265.000,265.000,265.000,265.000,265.000,265.000,265.000,265.000
mean,14.192,3.887,4.758,4.585,4.626,6.687,1.893,3.845,3.438
std,9.890,1.149,0.735,0.989,0.941,4.981,1.441,2.516,2.343
min,1.000,1.000,1.000,1.000,1.000,1.000,0.267,1.000,1.000
25%,7.000,3.000,5.000,5.000,5.000,3.000,0.977,2.000,2.000
50%,12.000,4.000,5.000,5.000,5.000,5.000,1.516,3.000,3.000
75%,19.000,5.000,5.000,5.000,5.000,9.000,2.581,5.000,4.000
max,76.000,5.000,5.000,5.000,5.000,40.000,11.891,15.000,15.000

In [23]:
# ============================================================
# PASO 4. SOCIAL DEBT INDEX v1
# ============================================================

sdi_variables = [
    "comment_count_norm",
    "macro_diversity_norm",
    "top_macro_frequency_norm",
    "top_micro_score_norm",
    "top_smell_frequency_norm",
    "top_risk_frequency_norm"
]

df_issue_adaptive["social_debt_index"] = (
    df_issue_adaptive[sdi_variables]
    .mean(axis=1)
)

display(
    df_issue_adaptive[
        [
            "issue_number",
            "social_debt_index"
        ]
    ]
    .sort_values(
        "social_debt_index",
        ascending=False
    )
    .head(20)
)

     issue_number  social_debt_index
76          60423           0.952381
53          59364           0.687698
13          18450           0.664266
61          59699           0.658568
8           18266           0.638281
166        134737           0.603483
38          58730           0.591427
7           18158           0.589832
170        134777           0.584090
137        134251           0.580749
68          60016           0.530878
80          60652           0.509025
92         133697           0.505313
10          18408           0.489900
6           18056           0.486757
90          61503           0.486697
5           17910           0.485677
243        136027           0.478122
23          20379           0.470650
21          19643           0.468439

In [24]:
# ============================================================
# PASO 5. COMPONENTES DE LOS ISSUES CON MAYOR SDI
# ============================================================

top_sdi_issues = (
    df_issue_adaptive
    .sort_values("social_debt_index", ascending=False)
    .head(20)
)

display(
    top_sdi_issues[
        [
            "issue_number",
            "social_debt_index",
            "comment_count",
            "macro_diversity",
            "top_macro_frequency",
            "top_micro_score",
            "top_smell_frequency",
            "top_risk_frequency"
        ]
    ]
)

,issue_number,social_debt_index,comment_count,macro_diversity,top_macro_frequency,top_micro_score,top_smell_frequency,top_risk_frequency
76,60423,0.952381,76,5,40,11.890820,13,13
53,59364,0.687698,47,5,25,7.378034,10,10
13,18450,0.664266,38,4,16,4.424321,15,15
61,59699,0.658568,44,5,22,8.366035,11,7
8,18266,0.638281,42,5,24,5.004502,8,12
166,134737,0.603483,41,5,25,4.925355,8,9
38,58730,0.591427,28,5,21,5.630995,10,9
7,18158,0.589832,39,5,13,3.708487,12,10
170,134777,0.584090,18,3,15,5.966587,15,14
137,134251,0.580749,42,5,17,4.738974,10,8
68,60016,0.530878,25,5,17,5.556048,8,8
80,60652,0.509025,33,5,12,2.621819,9,9
92,133697,0.505313,31,5,14,5.397881,7,7
10,18408,0.489900,34,5,19,4.028321,7,5
6,18056,0.486757,41,4,15,4.331518,7,8
90,61503,0.486697,30,5,14,3.424293,8,7
5,17910,0.485677,33,5,12,2.654006,7,9
243,136027,0.478122,26,4,19,5.692149,7,7
23,20379,0.470650,19,5,11,3.243538,10,7
21,19643,0.468439,42,5,14,3.612157,6,5

In [25]:
# ============================================================
# PASO 6. CLASIFICAR NIVEL DE DEUDA SOCIAL
# Low / Medium / High
# ============================================================

q1 = df_issue_adaptive["social_debt_index"].quantile(0.33)
q2 = df_issue_adaptive["social_debt_index"].quantile(0.66)

def classify_social_debt_level(score):
    if score <= q1:
        return "Low Social Debt"
    elif score <= q2:
        return "Medium Social Debt"
    else:
        return "High Social Debt"

df_issue_adaptive["social_debt_level"] = (
    df_issue_adaptive["social_debt_index"]
    .apply(classify_social_debt_level)
)

print("Umbral Low/Medium:", q1)
print("Umbral Medium/High:", q2)

display(
    df_issue_adaptive["social_debt_level"]
    .value_counts()
    .reset_index()
    .rename(columns={"index": "social_debt_level", "social_debt_level": "count"})
)

Umbral Low/Medium: 0.20017382534624975
Umbral Medium/High: 0.2921888145230001

                count  count
0    High Social Debt     90
1     Low Social Debt     88
2  Medium Social Debt     87

In [26]:
# ============================================================
# PASO 7. VALIDACIÓN INTERNA DEL SOCIAL DEBT INDEX
# Comparación de variables por nivel de deuda social
# ============================================================

validation_by_level = (
    df_issue_adaptive
    .groupby("social_debt_level")
    [
        [
            "social_debt_index",
            "comment_count",
            "macro_diversity",
            "top_macro_frequency",
            "top_micro_score",
            "top_smell_frequency",
            "top_risk_frequency"
        ]
    ]
    .mean()
    .round(3)
)

display(validation_by_level)

,social_debt_index,comment_count,macro_diversity,top_macro_frequency,top_micro_score,top_smell_frequency,top_risk_frequency
social_debt_level,,,,,,,
High Social Debt,0.407,24.356,4.656,11.344,3.203,6.267,5.556
Low Social Debt,0.120,5.534,2.784,2.943,0.854,1.886,1.693
Medium Social Debt,0.249,12.437,4.207,5.655,1.587,3.322,3.011

In [27]:
# ============================================================
# PASO 8. COMMUNITY SMELLS DOMINANTES POR NIVEL DE DEUDA SOCIAL
# ============================================================

from collections import Counter
import pandas as pd

rows = []

for level, group in df_issue_adaptive.groupby("social_debt_level"):
    smell_counter = Counter()

    for smells in group["dominant_community_smells"]:
        for smell, freq in smells:
            smell_counter[smell] += freq

    for smell, frequency in smell_counter.most_common(10):
        rows.append({
            "social_debt_level": level,
            "community_smell": smell,
            "frequency": frequency
        })

smells_by_level = pd.DataFrame(rows)

display(smells_by_level)

,social_debt_level,community_smell,frequency
0,High Social Debt,"['Missing Link', 'Socio-Technical Congruence G...",278
1,High Social Debt,['Socio-Technical Congruence Gap'],220
2,High Social Debt,"['Missing Link', 'Power Distance']",186
3,High Social Debt,['Power Distance'],144
4,High Social Debt,"['Missing Link', 'Organizational Silo', 'Socio...",113
5,High Social Debt,"['Missing Link', 'Organizational Silo']",105
6,High Social Debt,"['Organizational Silo', 'Socio-Technical Congr...",102
7,High Social Debt,['Missing Link'],75
8,High Social Debt,"['Socio-Technical Congruence Gap', 'Truck Fact...",67
9,High Social Debt,"['Knowledge Silos', 'Truck Factor']",64
10,Low Social Debt,"['Missing Link', 'Socio-Technical Congruence G...",50
11,Low Social Debt,"['Missing Link', 'Organizational Silo', 'Socio...",46
12,Low Social Debt,['Power Distance'],46
13,Low Social Debt,"['Organizational Silo', 'Power Distance']",42
14,Low Social Debt,"['Missing Link', 'Organizational Silo']",30
15,Low Social Debt,['Socio-Technical Congruence Gap'],26
16,Low Social Debt,"['Knowledge Silos', 'Truck Factor']",25
17,Low Social Debt,"['Organizational Silo', 'Socio-Technical Congr...",24
18,Low Social Debt,"['Missing Link', 'Organizational Silo', 'Power...",19
19,Low Social Debt,"['Missing Link', 'Organizational Silo', 'Socio...",19
20,Medium Social Debt,"['Missing Link', 'Socio-Technical Congruence G...",105
21,Medium Social Debt,['Socio-Technical Congruence Gap'],89
22,Medium Social Debt,"['Missing Link', 'Organizational Silo', 'Socio...",81
23,Medium Social Debt,"['Missing Link', 'Power Distance']",74
24,Medium Social Debt,['Power Distance'],67
25,Medium Social Debt,"['Missing Link', 'Organizational Silo']",60
26,Medium Social Debt,"['Organizational Silo', 'Socio-Technical Congr...",58
27,Medium Social Debt,"['Missing Link', 'Organizational Silo', 'Socio...",49
28,Medium Social Debt,"['Organizational Silo', 'Power Distance']",34
29,Medium Social Debt,['Missing Link'],31

In [28]:
# ============================================================
# PASO 9. RIESGOS DOMINANTES POR NIVEL DE DEUDA SOCIAL
# ============================================================

from collections import Counter
import pandas as pd

rows = []

for level, group in df_issue_adaptive.groupby("social_debt_level"):
    risk_counter = Counter()

    for risks in group["dominant_risks"]:
        for risk, freq in risks:
            risk_counter[risk] += freq

    for risk, frequency in risk_counter.most_common(10):
        rows.append({
            "social_debt_level": level,
            "risk": risk,
            "frequency": frequency
        })

risks_by_level = pd.DataFrame(rows)

display(risks_by_level)

,social_debt_level,risk,frequency
0,High Social Debt,['RSK-012_ReworkRisk'],215
1,High Social Debt,"['RSK-010_MiscommunicationRisk', 'RSK-020_Misi...",155
2,High Social Debt,"['RSK-013_TechnicalMaintenanceRisk', 'RSK-021_...",131
3,High Social Debt,"['RSK-005_Documentation_Gaps_Risk', 'RSK-013_T...",98
4,High Social Debt,"['RSK-013_TechnicalMaintenanceRisk', 'RSK-021_...",92
5,High Social Debt,"['RSK-005_Documentation_Gaps_Risk', 'RSK-013_T...",80
6,High Social Debt,['RSK-005_Documentation_Gaps_Risk'],70
7,High Social Debt,['RSK-026_ToolingRisk'],67
8,High Social Debt,['RSK-002_Feedback_Delays_Risk'],65
9,High Social Debt,"['RSK-011_KnowledgeLossRisk', 'RSK-013_Technic...",52
10,Low Social Debt,['RSK-012_ReworkRisk'],80
11,Low Social Debt,['RSK-002_Feedback_Delays_Risk'],29
12,Low Social Debt,"['RSK-002_Feedback_Delays_Risk', 'RSK-003_Feed...",25
13,Low Social Debt,"['RSK-011_KnowledgeLossRisk', 'RSK-013_Technic...",25
14,Low Social Debt,"['RSK-005_Documentation_Gaps_Risk', 'RSK-012_R...",22
15,Low Social Debt,['RSK-026_ToolingRisk'],18
16,Low Social Debt,['RSK-024_ValidationBottleneckRisk'],16
17,Low Social Debt,"['RSK-004_Language_Miscommunication_Risk', 'RS...",15
18,Low Social Debt,"['RSK-024_ValidationBottleneckRisk', 'RSK-026_...",14
19,Low Social Debt,['RSK-005_Documentation_Gaps_Risk'],13
20,Medium Social Debt,['RSK-012_ReworkRisk'],117
21,Medium Social Debt,"['RSK-010_MiscommunicationRisk', 'RSK-020_Misi...",56
22,Medium Social Debt,"['RSK-013_TechnicalMaintenanceRisk', 'RSK-021_...",50
23,Medium Social Debt,"['RSK-005_Documentation_Gaps_Risk', 'RSK-013_T...",41
24,Medium Social Debt,['RSK-002_Feedback_Delays_Risk'],36
25,Medium Social Debt,['RSK-026_ToolingRisk'],35
26,Medium Social Debt,"['RSK-024_ValidationBottleneckRisk', 'RSK-026_...",30
27,Medium Social Debt,"['RSK-013_TechnicalMaintenanceRisk', 'RSK-021_...",29
28,Medium Social Debt,['RSK-003_Feedback_Delays_Risk'],29
29,Medium Social Debt,"['RSK-005_Documentation_Gaps_Risk', 'RSK-012_R...",26

In [30]:
# ============================================================
# PASO 10. MICROCAUSAS DOMINANTES POR NIVEL DE DEUDA SOCIAL
# ============================================================

from collections import Counter
import pandas as pd

rows = []

for level, group in df_issue_adaptive.groupby("social_debt_level"):
    micro_counter = Counter()

    for micros in group["dominant_microcauses"]:
        for micro, score in micros:
            micro_counter[micro] += score

    for micro, score in micro_counter.most_common(15):
        rows.append({
            "social_debt_level": level,
            "microcause": micro,
            "aggregated_score": score
        })

microcauses_by_level = pd.DataFrame(rows)

display(microcauses_by_level)

,social_debt_level,microcause,aggregated_score
0,High Social Debt,Compatibility Constraints,186.964621
1,High Social Debt,System configuration constraints,116.860125
2,High Social Debt,Lack of Interface Clarification,102.372815
3,High Social Debt,Task rework due to misalignment,91.920933
4,High Social Debt,Coordination misalignment for technical valida...,85.070238
5,High Social Debt,Inefficient or inadequate tools,54.824360
6,High Social Debt,Unclear or ambiguous communication,39.100093
7,High Social Debt,Restricted Information Flow,35.636989
8,High Social Debt,Technical complexity due to dependencies,34.111647
9,High Social Debt,Request for Technical Validation Support,22.510397
10,High Social Debt,Preservation of prior system behavior,19.479368
11,High Social Debt,Miscommunication In Task Handover,12.706568
12,High Social Debt,Lack of technical documentation,11.397986
13,High Social Debt,Repository access limitation,9.021157
14,High Social Debt,Constraint due to ticket status for review,7.214477
15,Low Social Debt,Task rework due to misalignment,39.857773
16,Low Social Debt,Coordination misalignment for technical valida...,33.862981
17,Low Social Debt,Constraint due to ticket status for review,18.013145
18,Low Social Debt,Compatibility Constraints,15.184742
19,Low Social Debt,Restricted Information Flow,15.172388
20,Low Social Debt,Inefficient or inadequate tools,13.899667
21,Low Social Debt,Blockage due to approval requirements,13.511685
22,Low Social Debt,System configuration constraints,11.925790
23,Low Social Debt,Request for Technical Validation Support,10.843098
24,Low Social Debt,Lack of Interface Clarification,7.097313
25,Low Social Debt,Miscommunication In Task Handover,6.980439
26,Low Social Debt,Lack of technical documentation,6.110055
27,Low Social Debt,Repository access limitation,5.096706
28,Low Social Debt,Blockage due to triage process,3.733327
29,Low Social Debt,Unilateral Task Assignment,3.595462
30,Medium Social Debt,Compatibility Constraints,69.118865
31,Medium Social Debt,System configuration constraints,53.542817
32,Medium Social Debt,Task rework due to misalignment,53.173206
33,Medium Social Debt,Coordination misalignment for technical valida...,49.333316
34,Medium Social Debt,Inefficient or inadequate tools,39.401886
35,Medium Social Debt,Lack of Interface Clarification,35.961175
36,Medium Social Debt,Request for Technical Validation Support,21.636517
37,Medium Social Debt,Restricted Information Flow,19.404772
38,Medium Social Debt,Unclear or ambiguous communication,15.706945
39,Medium Social Debt,Technical complexity due to dependencies,14.372099
40,Medium Social Debt,Delayed Communication,9.589089
41,Medium Social Debt,Blockage due to approval requirements,8.723196
42,Medium Social Debt,Preservation of prior system behavior,8.092073
43,Medium Social Debt,Misinterpretation of information,7.069416
44,Medium Social Debt,Repository access limitation,7.048021

In [31]:
# ============================================================
# PASO 11. MACROCAUSAS DOMINANTES POR NIVEL DE DEUDA SOCIAL
# ============================================================

from collections import Counter
import pandas as pd

rows = []

for level, group in df_issue_adaptive.groupby("social_debt_level"):
    macro_counter = Counter()

    for macros in group["dominant_macrocauses"]:
        for macro, freq in macros:
            macro_counter[macro] += freq

    for macro, frequency in macro_counter.most_common(10):
        rows.append({
            "social_debt_level": level,
            "macrocause": macro,
            "frequency": frequency
        })

macrocauses_by_level = pd.DataFrame(rows)

display(macrocauses_by_level)

,social_debt_level,macrocause,frequency
0,High Social Debt,"Technical complexity, compatibility, and syste...",740
1,High Social Debt,Coordination and workflow misalignment,536
2,High Social Debt,Communication and shared understanding breakdowns,364
3,High Social Debt,"Resource, tooling, access, and validation depe...",221
4,High Social Debt,"Knowledge, documentation, and standards defici...",135
5,High Social Debt,Organizational and procedural workflow constra...,115
6,High Social Debt,Collaboration and interpersonal tensions,41
7,Low Social Debt,Coordination and workflow misalignment,189
8,Low Social Debt,Organizational and procedural workflow constra...,92
9,Low Social Debt,"Resource, tooling, access, and validation depe...",73
10,Low Social Debt,"Technical complexity, compatibility, and syste...",73
11,Low Social Debt,"Knowledge, documentation, and standards defici...",36
12,Low Social Debt,Communication and shared understanding breakdowns,21
13,Low Social Debt,Collaboration and interpersonal tensions,3
14,Medium Social Debt,"Technical complexity, compatibility, and syste...",312
15,Medium Social Debt,Coordination and workflow misalignment,286
16,Medium Social Debt,Communication and shared understanding breakdowns,177
17,Medium Social Debt,"Resource, tooling, access, and validation depe...",152
18,Medium Social Debt,Organizational and procedural workflow constra...,70
19,Medium Social Debt,"Knowledge, documentation, and standards defici...",57
20,Medium Social Debt,Collaboration and interpersonal tensions,16

In [32]:
# ============================================================
# PASO 12. PERFIL RESUMEN DEL MODELO ADAPTATIVO POR NIVEL
# ============================================================

summary_profile = (
    df_issue_adaptive
    .groupby("social_debt_level")
    .agg(
        issue_count=("issue_number", "count"),
        mean_sdi=("social_debt_index", "mean"),
        mean_comments=("comment_count", "mean"),
        mean_macro_diversity=("macro_diversity", "mean"),
        mean_top_macro_frequency=("top_macro_frequency", "mean"),
        mean_top_micro_score=("top_micro_score", "mean"),
        mean_top_smell_frequency=("top_smell_frequency", "mean"),
        mean_top_risk_frequency=("top_risk_frequency", "mean")
    )
    .round(3)
    .reset_index()
)

display(summary_profile)

,social_debt_level,issue_count,mean_sdi,mean_comments,mean_macro_diversity,mean_top_macro_frequency,mean_top_micro_score,mean_top_smell_frequency,mean_top_risk_frequency
0,High Social Debt,90,0.407,24.356,4.656,11.344,3.203,6.267,5.556
1,Low Social Debt,88,0.120,5.534,2.784,2.943,0.854,1.886,1.693
2,Medium Social Debt,87,0.249,12.437,4.207,5.655,1.587,3.322,3.011

In [33]:
# ============================================================
# PASO 13. EXPORTAR RESULTADO FINAL DEL MODELO ADAPTATIVO
# ============================================================

output_file = "adaptive_social_debt_issue_model.xlsx"

df_issue_adaptive.to_excel(output_file, index=False)

print("Archivo exportado:", output_file)
print("Dimensiones:", df_issue_adaptive.shape)

Archivo exportado: adaptive_social_debt_issue_model.xlsx
Dimensiones: (265, 26)

In [34]:
# ============================================================
# FASE IV. MODELOS PREDICTIVOS
# PASO 14. DISTRIBUCIÓN DE LA VARIABLE OBJETIVO
# ============================================================

display(
    df_issue_adaptive["social_debt_level"]
    .value_counts()
    .reset_index()
    .rename(columns={
        "index": "social_debt_level",
        "social_debt_level": "count"
    })
)

display(
    df_issue_adaptive["social_debt_level"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
    .reset_index()
    .rename(columns={
        "index": "social_debt_level",
        "social_debt_level": "percentage"
    })
)

                count  count
0    High Social Debt     90
1     Low Social Debt     88
2  Medium Social Debt     87

           percentage  proportion
0    High Social Debt       33.96
1     Low Social Debt       33.21
2  Medium Social Debt       32.83

In [35]:
# ============================================================
# FASE IV. MODELOS PREDICTIVOS
# PASO 15. MODELO BASELINE TF-IDF + LOGISTIC REGRESSION
# Objetivo: predecir social_debt_level desde issue_text
# ============================================================

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, f1_score, confusion_matrix
import pandas as pd

# -----------------------------
# 1. Definir X e y
# -----------------------------
X = df_issue_adaptive["issue_text"].astype(str)
y = df_issue_adaptive["social_debt_level"]

# -----------------------------
# 2. División train/test estratificada
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

# -----------------------------
# 3. Pipeline baseline
# -----------------------------
baseline_model = Pipeline([
    (
        "tfidf",
        TfidfVectorizer(
            max_features=5000,
            ngram_range=(1, 2),
            min_df=2
        )
    ),
    (
        "clf",
        LogisticRegression(
            max_iter=1000,
            class_weight="balanced",
            random_state=42
        )
    )
])

# -----------------------------
# 4. Entrenar
# -----------------------------
baseline_model.fit(X_train, y_train)

# -----------------------------
# 5. Predecir
# -----------------------------
y_pred = baseline_model.predict(X_test)

# -----------------------------
# 6. Métricas
# -----------------------------
accuracy = accuracy_score(y_test, y_pred)
macro_f1 = f1_score(y_test, y_pred, average="macro")
weighted_f1 = f1_score(y_test, y_pred, average="weighted")

print("Accuracy:", round(accuracy, 4))
print("Macro F1:", round(macro_f1, 4))
print("Weighted F1:", round(weighted_f1, 4))

print("\nClassification report:")
print(classification_report(y_test, y_pred))

# -----------------------------
# 7. Matriz de confusión
# -----------------------------
labels = baseline_model.classes_

cm = confusion_matrix(y_test, y_pred, labels=labels)

cm_df = pd.DataFrame(
    cm,
    index=[f"True {label}" for label in labels],
    columns=[f"Pred {label}" for label in labels]
)

display(cm_df)

Accuracy: 0.5625
Macro F1: 0.5547
Weighted F1: 0.5576

Classification report:
                    precision    recall  f1-score   support

  High Social Debt       0.58      0.67      0.62        27
   Low Social Debt       0.73      0.70      0.72        27
Medium Social Debt       0.35      0.31      0.33        26

          accuracy                           0.56        80
         macro avg       0.55      0.56      0.55        80
      weighted avg       0.56      0.56      0.56        80

,Pred High Social Debt,Pred Low Social Debt,Pred Medium Social Debt
True High Social Debt,18,1,8
True Low Social Debt,1,19,7
True Medium Social Debt,12,6,8

In [36]:
# ============================================================
# FASE IV. MODELOS PREDICTIVOS
# PASO 16. MODELO TF-IDF + LINEAR SVM
# Objetivo: predecir social_debt_level desde issue_text
# ============================================================

from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, accuracy_score, f1_score, confusion_matrix
import pandas as pd

svm_model = Pipeline([
    (
        "tfidf",
        TfidfVectorizer(
            max_features=5000,
            ngram_range=(1, 2),
            min_df=2
        )
    ),
    (
        "clf",
        LinearSVC(
            class_weight="balanced",
            random_state=42
        )
    )
])

# Entrenar
svm_model.fit(X_train, y_train)

# Predecir
y_pred_svm = svm_model.predict(X_test)

# Métricas
accuracy_svm = accuracy_score(y_test, y_pred_svm)
macro_f1_svm = f1_score(y_test, y_pred_svm, average="macro")
weighted_f1_svm = f1_score(y_test, y_pred_svm, average="weighted")

print("Accuracy:", round(accuracy_svm, 4))
print("Macro F1:", round(macro_f1_svm, 4))
print("Weighted F1:", round(weighted_f1_svm, 4))

print("\nClassification report:")
print(classification_report(y_test, y_pred_svm))

# Matriz de confusión
labels = svm_model.classes_

cm_svm = confusion_matrix(y_test, y_pred_svm, labels=labels)

cm_svm_df = pd.DataFrame(
    cm_svm,
    index=[f"True {label}" for label in labels],
    columns=[f"Pred {label}" for label in labels]
)

display(cm_svm_df)

Accuracy: 0.5375
Macro F1: 0.5108
Weighted F1: 0.5142

Classification report:
                    precision    recall  f1-score   support

  High Social Debt       0.57      0.74      0.65        27
   Low Social Debt       0.64      0.67      0.65        27
Medium Social Debt       0.29      0.19      0.23        26

          accuracy                           0.54        80
         macro avg       0.50      0.53      0.51        80
      weighted avg       0.51      0.54      0.51        80

,Pred High Social Debt,Pred Low Social Debt,Pred Medium Social Debt
True High Social Debt,20,1,6
True Low Social Debt,3,18,6
True Medium Social Debt,12,9,5

In [37]:
# ============================================================
# FASE IV. MODELOS PREDICTIVOS
# PASO 17. MODELO CON VARIABLES ESTRUCTURADAS DEL MODELO ADAPTATIVO
# Random Forest
# ============================================================

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, f1_score, confusion_matrix
import pandas as pd

# -----------------------------
# 1. Variables estructuradas
# -----------------------------
structured_features = [
    "comment_count",
    "macro_diversity",
    "top_macro_frequency",
    "top_micro_score",
    "top_smell_frequency",
    "top_risk_frequency"
]

X_struct = df_issue_adaptive[structured_features]
y_struct = df_issue_adaptive["social_debt_level"]

# -----------------------------
# 2. División train/test estratificada
# -----------------------------
X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(
    X_struct,
    y_struct,
    test_size=0.30,
    random_state=42,
    stratify=y_struct
)

# -----------------------------
# 3. Modelo Random Forest
# -----------------------------
rf_model = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    class_weight="balanced",
    random_state=42
)

# -----------------------------
# 4. Entrenar
# -----------------------------
rf_model.fit(X_train_s, y_train_s)

# -----------------------------
# 5. Predecir
# -----------------------------
y_pred_rf = rf_model.predict(X_test_s)

# -----------------------------
# 6. Métricas
# -----------------------------
accuracy_rf = accuracy_score(y_test_s, y_pred_rf)
macro_f1_rf = f1_score(y_test_s, y_pred_rf, average="macro")
weighted_f1_rf = f1_score(y_test_s, y_pred_rf, average="weighted")

print("Accuracy:", round(accuracy_rf, 4))
print("Macro F1:", round(macro_f1_rf, 4))
print("Weighted F1:", round(weighted_f1_rf, 4))

print("\nClassification report:")
print(classification_report(y_test_s, y_pred_rf))

# -----------------------------
# 7. Matriz de confusión
# -----------------------------
labels = rf_model.classes_

cm_rf = confusion_matrix(y_test_s, y_pred_rf, labels=labels)

cm_rf_df = pd.DataFrame(
    cm_rf,
    index=[f"True {label}" for label in labels],
    columns=[f"Pred {label}" for label in labels]
)

display(cm_rf_df)

# -----------------------------
# 8. Importancia de variables
# -----------------------------
feature_importance = pd.DataFrame({
    "feature": structured_features,
    "importance": rf_model.feature_importances_
}).sort_values("importance", ascending=False)

display(feature_importance)

Accuracy: 0.9
Macro F1: 0.9017
Weighted F1: 0.9022

Classification report:
                    precision    recall  f1-score   support

  High Social Debt       0.96      0.85      0.90        27
   Low Social Debt       1.00      0.89      0.94        27
Medium Social Debt       0.78      0.96      0.86        26

          accuracy                           0.90        80
         macro avg       0.91      0.90      0.90        80
      weighted avg       0.91      0.90      0.90        80

,Pred High Social Debt,Pred Low Social Debt,Pred Medium Social Debt
True High Social Debt,23,0,4
True Low Social Debt,0,24,3
True Medium Social Debt,1,0,25

               feature  importance
0        comment_count    0.314067
3      top_micro_score    0.193392
1      macro_diversity    0.177386
2  top_macro_frequency    0.133180
4  top_smell_frequency    0.103816
5   top_risk_frequency    0.078158

In [38]:
# ============================================================
# PASO 18. TABLA COMPARATIVA DE MODELOS
# ============================================================

model_results = pd.DataFrame([
    {
        "model": "TF-IDF + Logistic Regression",
        "input_type": "Issue text",
        "accuracy": accuracy,
        "macro_f1": macro_f1,
        "weighted_f1": weighted_f1
    },
    {
        "model": "TF-IDF + Linear SVM",
        "input_type": "Issue text",
        "accuracy": accuracy_svm,
        "macro_f1": macro_f1_svm,
        "weighted_f1": weighted_f1_svm
    },
    {
        "model": "Random Forest",
        "input_type": "Adaptive structured features",
        "accuracy": accuracy_rf,
        "macro_f1": macro_f1_rf,
        "weighted_f1": weighted_f1_rf
    }
])

model_results = model_results.round(4)

display(model_results)

,model,input_type,accuracy,macro_f1,weighted_f1
0,TF-IDF + Logistic Regression,Issue text,0.5625,0.5547,0.5576
1,TF-IDF + Linear SVM,Issue text,0.5375,0.5108,0.5142
2,Random Forest,Adaptive structured features,0.9000,0.9017,0.9022

In [39]:
# ============================================================
# PASO 19. EXPORTAR TABLA COMPARATIVA DE MODELOS
# ============================================================

output_models = "model_comparison_social_debt.xlsx"

model_results.to_excel(output_models, index=False)

print("Archivo exportado:", output_models)
print("Dimensiones:", model_results.shape)

Archivo exportado: model_comparison_social_debt.xlsx
Dimensiones: (3, 5)

In [40]:
# ============================================================
# PASO 20. CROSS-VALIDATION ESTRATIFICADA
# Comparación más robusta de modelos
# ============================================================

from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.metrics import make_scorer, accuracy_score, f1_score
import pandas as pd

# -----------------------------
# 1. Definir validación cruzada
# -----------------------------
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# -----------------------------
# 2. Métricas
# -----------------------------
scoring = {
    "accuracy": "accuracy",
    "macro_f1": "f1_macro",
    "weighted_f1": "f1_weighted"
}

# -----------------------------
# 3. Modelos a comparar
# -----------------------------
models_cv = {
    "TF-IDF + Logistic Regression": baseline_model,
    "TF-IDF + Linear SVM": svm_model,
    "Random Forest + Adaptive Features": rf_model
}

# -----------------------------
# 4. Datos de entrada por modelo
# -----------------------------
model_inputs = {
    "TF-IDF + Logistic Regression": (X, y),
    "TF-IDF + Linear SVM": (X, y),
    "Random Forest + Adaptive Features": (X_struct, y_struct)
}

# -----------------------------
# 5. Ejecutar cross-validation
# -----------------------------
cv_results_rows = []

for model_name, model in models_cv.items():
    X_model, y_model = model_inputs[model_name]

    scores = cross_validate(
        model,
        X_model,
        y_model,
        cv=cv,
        scoring=scoring,
        return_train_score=False
    )

    cv_results_rows.append({
        "model": model_name,
        "accuracy_mean": scores["test_accuracy"].mean(),
        "accuracy_std": scores["test_accuracy"].std(),
        "macro_f1_mean": scores["test_macro_f1"].mean(),
        "macro_f1_std": scores["test_macro_f1"].std(),
        "weighted_f1_mean": scores["test_weighted_f1"].mean(),
        "weighted_f1_std": scores["test_weighted_f1"].std()
    })

cv_results = pd.DataFrame(cv_results_rows).round(4)

display(cv_results)

,model,accuracy_mean,accuracy_std,macro_f1_mean,macro_f1_std,weighted_f1_mean,weighted_f1_std
0,TF-IDF + Logistic Regression,0.6528,0.0627,0.6345,0.0660,0.6355,0.0660
1,TF-IDF + Linear SVM,0.5887,0.0577,0.5558,0.0552,0.5577,0.0560
2,Random Forest + Adaptive Features,0.9094,0.0220,0.9094,0.0220,0.9096,0.0217

In [41]:
# ============================================================
# PASO 21. EXPORTAR RESULTADOS DE CROSS-VALIDATION
# ============================================================

output_cv = "cross_validation_social_debt_models.xlsx"

cv_results.to_excel(output_cv, index=False)

print("Archivo exportado:", output_cv)
print("Dimensiones:", cv_results.shape)

Archivo exportado: cross_validation_social_debt_models.xlsx
Dimensiones: (3, 7)

In [42]:
# ============================================================
# PASO 22. IMPORTANCIA PROMEDIO DE VARIABLES
# Random Forest con validación cruzada
# ============================================================

from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

feature_importance_rows = []

for fold, (train_idx, test_idx) in enumerate(cv.split(X_struct, y_struct), start=1):

    X_train_fold = X_struct.iloc[train_idx]
    X_test_fold = X_struct.iloc[test_idx]
    y_train_fold = y_struct.iloc[train_idx]
    y_test_fold = y_struct.iloc[test_idx]

    rf_fold = RandomForestClassifier(
        n_estimators=300,
        max_depth=None,
        class_weight="balanced",
        random_state=42
    )

    rf_fold.fit(X_train_fold, y_train_fold)

    for feature, importance in zip(structured_features, rf_fold.feature_importances_):
        feature_importance_rows.append({
            "fold": fold,
            "feature": feature,
            "importance": importance
        })

feature_importance_cv = pd.DataFrame(feature_importance_rows)

feature_importance_summary = (
    feature_importance_cv
    .groupby("feature")
    .agg(
        mean_importance=("importance", "mean"),
        std_importance=("importance", "std")
    )
    .sort_values("mean_importance", ascending=False)
    .round(4)
    .reset_index()
)

display(feature_importance_summary)

               feature  mean_importance  std_importance
0        comment_count           0.3485          0.0081
1      macro_diversity           0.1619          0.0090
2      top_micro_score           0.1578          0.0167
3  top_smell_frequency           0.1246          0.0217
4  top_macro_frequency           0.1194          0.0055
5   top_risk_frequency           0.0878          0.0155

In [ ]:
# ============================================================
# PASO 23. SBERT + LOGISTIC REGRESSION
# Objetivo: predecir social_debt_level desde issue_text
# ============================================================

from sentence_transformers import SentenceTransformer
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

# -----------------------------
# 1. Definir X e y
# -----------------------------
X_text = df_issue_adaptive["issue_text"].astype(str).tolist()
y_sbert = df_issue_adaptive["social_debt_level"]

# -----------------------------
# 2. Cargar modelo SBERT
# -----------------------------
sbert_model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

# -----------------------------
# 3. Generar embeddings
# -----------------------------
X_sbert = sbert_model.encode(
    X_text,
    show_progress_bar=True,
    normalize_embeddings=True
)

print("Dimensiones embeddings:", X_sbert.shape)

In [ ]:
# ============================================================
# PASO 24. SBERT + LOGISTIC REGRESSION
# Validación cruzada estratificada
# ============================================================

from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
import pandas as pd

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

sbert_lr_model = Pipeline([
    (
        "scaler",
        StandardScaler()
    ),
    (
        "clf",
        LogisticRegression(
            max_iter=2000,
            class_weight="balanced",
            random_state=42
        )
    )
])

scoring = {
    "accuracy": "accuracy",
    "macro_f1": "f1_macro",
    "weighted_f1": "f1_weighted"
}

scores_sbert_lr = cross_validate(
    sbert_lr_model,
    X_sbert,
    y_sbert,
    cv=cv,
    scoring=scoring,
    return_train_score=False
)

sbert_lr_results = pd.DataFrame([{
    "model": "SBERT + Logistic Regression",
    "input_type": "Issue text embeddings",
    "accuracy_mean": scores_sbert_lr["test_accuracy"].mean(),
    "accuracy_std": scores_sbert_lr["test_accuracy"].std(),
    "macro_f1_mean": scores_sbert_lr["test_macro_f1"].mean(),
    "macro_f1_std": scores_sbert_lr["test_macro_f1"].std(),
    "weighted_f1_mean": scores_sbert_lr["test_weighted_f1"].mean(),
    "weighted_f1_std": scores_sbert_lr["test_weighted_f1"].std()
}]).round(4)

display(sbert_lr_results)

,model,input_type,accuracy_mean,accuracy_std,macro_f1_mean,macro_f1_std,weighted_f1_mean,weighted_f1_std
0,SBERT + Logistic Regression,Issue text embeddings,0.4226,0.0456,0.4184,0.0467,0.4189,0.0471

In [ ]:
# ============================================================
# PASO 25. TABLA FINAL COMPARATIVA CON SBERT
# ============================================================

final_model_results = pd.DataFrame([
    {
        "model": "TF-IDF + Logistic Regression",
        "input_type": "Issue text",
        "accuracy_mean": cv_results.loc[
            cv_results["model"] == "TF-IDF + Logistic Regression",
            "accuracy_mean"
        ].values[0],
        "macro_f1_mean": cv_results.loc[
            cv_results["model"] == "TF-IDF + Logistic Regression",
            "macro_f1_mean"
        ].values[0],
        "weighted_f1_mean": cv_results.loc[
            cv_results["model"] == "TF-IDF + Logistic Regression",
            "weighted_f1_mean"
        ].values[0]
    },
    {
        "model": "TF-IDF + Linear SVM",
        "input_type": "Issue text",
        "accuracy_mean": cv_results.loc[
            cv_results["model"] == "TF-IDF + Linear SVM",
            "accuracy_mean"
        ].values[0],
        "macro_f1_mean": cv_results.loc[
            cv_results["model"] == "TF-IDF + Linear SVM",
            "macro_f1_mean"
        ].values[0],
        "weighted_f1_mean": cv_results.loc[
            cv_results["model"] == "TF-IDF + Linear SVM",
            "weighted_f1_mean"
        ].values[0]
    },
    {
        "model": "SBERT + Logistic Regression",
        "input_type": "Issue text embeddings",
        "accuracy_mean": sbert_lr_results["accuracy_mean"].values[0],
        "macro_f1_mean": sbert_lr_results["macro_f1_mean"].values[0],
        "weighted_f1_mean": sbert_lr_results["weighted_f1_mean"].values[0]
    },
    {
        "model": "Random Forest + Adaptive Features",
        "input_type": "Adaptive structured features",
        "accuracy_mean": cv_results.loc[
            cv_results["model"] == "Random Forest + Adaptive Features",
            "accuracy_mean"
        ].values[0],
        "macro_f1_mean": cv_results.loc[
            cv_results["model"] == "Random Forest + Adaptive Features",
            "macro_f1_mean"
        ].values[0],
        "weighted_f1_mean": cv_results.loc[
            cv_results["model"] == "Random Forest + Adaptive Features",
            "weighted_f1_mean"
        ].values[0]
    }
])

final_model_results = final_model_results.round(4)

display(final_model_results)

,model,input_type,accuracy_mean,macro_f1_mean,weighted_f1_mean
0,TF-IDF + Logistic Regression,Issue text,0.6566,0.6377,0.6397
1,TF-IDF + Linear SVM,Issue text,0.6151,0.5790,0.5818
2,SBERT + Logistic Regression,Issue text embeddings,0.4226,0.4184,0.4189
3,Random Forest + Adaptive Features,Adaptive structured features,0.9472,0.9473,0.9475

In [ ]:
# =========================================================================
# PASO 26. COMPARACIÓN DE VARIOS MODELOS SBERT
# Objetivo: comparar embeddings semánticos para predecir social_debt_level
# =========================================================================

from sentence_transformers import SentenceTransformer
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
import pandas as pd

# -----------------------------
# 1. Datos
# -----------------------------
X_text = df_issue_adaptive["issue_text"].astype(str).tolist()
y_embed = df_issue_adaptive["social_debt_level"]

# -----------------------------
# 2. Validación cruzada
# -----------------------------
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scoring = {
    "accuracy": "accuracy",
    "macro_f1": "f1_macro",
    "weighted_f1": "f1_weighted"
}

# -----------------------------
# 3. Modelos de embeddings a comparar
# -----------------------------
embedding_models = [
    "paraphrase-multilingual-MiniLM-L12-v2",
    "all-MiniLM-L6-v2",
    "all-mpnet-base-v2",
    "multi-qa-mpnet-base-dot-v1"
]

embedding_results = []

# -----------------------------
# 4. Evaluar cada modelo
# -----------------------------
for model_name in embedding_models:

    print("\n======================================")
    print("Modelo de embeddings:", model_name)
    print("======================================")

    emb_model = SentenceTransformer(model_name)

    X_emb = emb_model.encode(
        X_text,
        show_progress_bar=True,
        normalize_embeddings=True
    )

    clf = Pipeline([
        ("scaler", StandardScaler()),
        (
            "clf",
            LogisticRegression(
                max_iter=2000,
                class_weight="balanced",
                random_state=42
            )
        )
    ])

    scores = cross_validate(
        clf,
        X_emb,
        y_embed,
        cv=cv,
        scoring=scoring,
        return_train_score=False
    )

    embedding_results.append({
        "embedding_model": model_name,
        "accuracy_mean": scores["test_accuracy"].mean(),
        "accuracy_std": scores["test_accuracy"].std(),
        "macro_f1_mean": scores["test_macro_f1"].mean(),
        "macro_f1_std": scores["test_macro_f1"].std(),
        "weighted_f1_mean": scores["test_weighted_f1"].mean(),
        "weighted_f1_std": scores["test_weighted_f1"].std(),
        "embedding_dim": X_emb.shape[1]
    })

embedding_results_df = (
    pd.DataFrame(embedding_results)
    .sort_values("macro_f1_mean", ascending=False)
    .round(4)
)

display(embedding_results_df)

======================================
Modelo de embeddings: paraphrase-multilingual-MiniLM-L12-v2
======================================

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/9 [00:00<?, ?it/s]

======================================
Modelo de embeddings: all-MiniLM-L6-v2
======================================

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/9 [00:00<?, ?it/s]

======================================
Modelo de embeddings: all-mpnet-base-v2
======================================

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/11.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/9 [00:00<?, ?it/s]

======================================
Modelo de embeddings: multi-qa-mpnet-base-dot-v1
======================================

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/212 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/9.95k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/9 [00:00<?, ?it/s]

,embedding_model,accuracy_mean,accuracy_std,macro_f1_mean,macro_f1_std,weighted_f1_mean,weighted_f1_std,embedding_dim
3,multi-qa-mpnet-base-dot-v1,0.4830,0.0542,0.4815,0.0503,0.4813,0.0497,768
2,all-mpnet-base-v2,0.4453,0.0151,0.4415,0.0184,0.4416,0.0176,768
0,paraphrase-multilingual-MiniLM-L12-v2,0.4226,0.0456,0.4184,0.0467,0.4189,0.0471,384
1,all-MiniLM-L6-v2,0.4000,0.0669,0.3987,0.0678,0.3981,0.0672,384

In [ ]:
# ============================================================
# PASO 27. TABLA FINAL COMPARATIVA DE TODOS LOS MODELOS
# ============================================================

best_embedding_row = (
    embedding_results_df
    .sort_values("macro_f1_mean", ascending=False)
    .iloc[0]
)

final_model_results = pd.DataFrame([
    {
        "model": "TF-IDF + Logistic Regression",
        "input_type": "Issue text",
        "accuracy_mean": cv_results.loc[
            cv_results["model"] == "TF-IDF + Logistic Regression",
            "accuracy_mean"
        ].values[0],
        "macro_f1_mean": cv_results.loc[
            cv_results["model"] == "TF-IDF + Logistic Regression",
            "macro_f1_mean"
        ].values[0],
        "weighted_f1_mean": cv_results.loc[
            cv_results["model"] == "TF-IDF + Logistic Regression",
            "weighted_f1_mean"
        ].values[0]
    },
    {
        "model": "TF-IDF + Linear SVM",
        "input_type": "Issue text",
        "accuracy_mean": cv_results.loc[
            cv_results["model"] == "TF-IDF + Linear SVM",
            "accuracy_mean"
        ].values[0],
        "macro_f1_mean": cv_results.loc[
            cv_results["model"] == "TF-IDF + Linear SVM",
            "macro_f1_mean"
        ].values[0],
        "weighted_f1_mean": cv_results.loc[
            cv_results["model"] == "TF-IDF + Linear SVM",
            "weighted_f1_mean"
        ].values[0]
    },
    {
        "model": f"Best SBERT ({best_embedding_row['embedding_model']})",
        "input_type": "Issue text embeddings",
        "accuracy_mean": best_embedding_row["accuracy_mean"],
        "macro_f1_mean": best_embedding_row["macro_f1_mean"],
        "weighted_f1_mean": best_embedding_row["weighted_f1_mean"]
    },
    {
        "model": "Random Forest + Adaptive Features",
        "input_type": "Adaptive structured features",
        "accuracy_mean": cv_results.loc[
            cv_results["model"] == "Random Forest + Adaptive Features",
            "accuracy_mean"
        ].values[0],
        "macro_f1_mean": cv_results.loc[
            cv_results["model"] == "Random Forest + Adaptive Features",
            "macro_f1_mean"
        ].values[0],
        "weighted_f1_mean": cv_results.loc[
            cv_results["model"] == "Random Forest + Adaptive Features",
            "weighted_f1_mean"
        ].values[0]
    }
])

final_model_results = (
    final_model_results
    .sort_values("macro_f1_mean", ascending=False)
    .round(4)
)

display(final_model_results)

,model,input_type,accuracy_mean,macro_f1_mean,weighted_f1_mean
3,Random Forest + Adaptive Features,Adaptive structured features,0.9472,0.9473,0.9475
0,TF-IDF + Logistic Regression,Issue text,0.6566,0.6377,0.6397
1,TF-IDF + Linear SVM,Issue text,0.6151,0.5790,0.5818
2,Best SBERT (multi-qa-mpnet-base-dot-v1),Issue text embeddings,0.4830,0.4815,0.4813

In [ ]:
# ============================================================
# PASO 28. EXPORTAR COMPARACIÓN FINAL DE MODELOS
# ============================================================

output_final_models = "final_model_comparison_social_debt.xlsx"

final_model_results.to_excel(output_final_models, index=False)

print("Archivo exportado:", output_final_models)
print("Dimensiones:", final_model_results.shape)

Archivo exportado: final_model_comparison_social_debt.xlsx
Dimensiones: (4, 5)

In [ ]:
# ============================================================
# PASO 29. RESUMEN INTERPRETATIVO POR NIVEL DE DEUDA SOCIAL
# ============================================================

# Tomamos los principales hallazgos que ya calculamos:
# summary_profile
# macrocauses_by_level
# microcauses_by_level
# smells_by_level
# risks_by_level

def top_items_as_text(df_source, level_col, item_col, value_col, level, top_n=3):
    subset = (
        df_source[df_source[level_col] == level]
        .sort_values(value_col, ascending=False)
        .head(top_n)
    )
    return "; ".join(
        [
            f"{row[item_col]} ({round(row[value_col], 3)})"
            for _, row in subset.iterrows()
        ]
    )

rows = []

for level in ["Low Social Debt", "Medium Social Debt", "High Social Debt"]:

    profile = summary_profile[
        summary_profile["social_debt_level"] == level
    ].iloc[0]

    rows.append({
        "social_debt_level": level,
        "issue_count": profile["issue_count"],
        "mean_sdi": profile["mean_sdi"],
        "mean_comments": profile["mean_comments"],
        "mean_macro_diversity": profile["mean_macro_diversity"],
        "top_macrocauses": top_items_as_text(
            macrocauses_by_level,
            "social_debt_level",
            "macrocause",
            "frequency",
            level,
            top_n=3
        ),
        "top_microcauses": top_items_as_text(
            microcauses_by_level,
            "social_debt_level",
            "microcause",
            "aggregated_score",
            level,
            top_n=3
        ),
        "top_community_smells": top_items_as_text(
            smells_by_level,
            "social_debt_level",
            "community_smell",
            "frequency",
            level,
            top_n=3
        ),
        "top_risks": top_items_as_text(
            risks_by_level,
            "social_debt_level",
            "risk",
            "frequency",
            level,
            top_n=3
        )
    })

adaptive_level_summary = pd.DataFrame(rows)

display(adaptive_level_summary)

,social_debt_level,issue_count,mean_sdi,mean_comments,mean_macro_diversity,top_macrocauses,top_microcauses,top_community_smells,top_risks
0,Low Social Debt,88,0.123,5.625,2.716,Coordination and workflow misalignment (178); ...,Task rework due to misalignment (33.972); Coor...,Missing Link (288); Organizational Silo (144);...,RSK-012_ReworkRisk (177); RSK-013_TechnicalMai...
1,Medium Social Debt,87,0.252,12.264,4.299,"Technical complexity, compatibility, and syste...",Compatibility Constraints (64.525); Task rewor...,Missing Link (638); Organizational Silo (259);...,RSK-012_ReworkRisk (285); RSK-005_Documentatio...
2,High Social Debt,90,0.410,24.433,4.633,"Technical complexity, compatibility, and syste...",Compatibility Constraints (170.641); System co...,Missing Link (1379); Socio-Technical Congruenc...,RSK-005_Documentation_Gaps_Risk (505); RSK-012...

In [ ]:
# ============================================================
# PASO 30. DIAGNÓSTICO ADAPTATIVO BÁSICO POR ISSUE
# ============================================================

def get_top_name(x):
    """
    Extrae el nombre del primer elemento de una lista tipo:
    [('Missing Link', 9), ('Power Distance', 4)]
    """
    if isinstance(x, list) and len(x) > 0:
        return x[0][0]
    return None

def get_top_value(x):
    """
    Extrae el valor del primer elemento de una lista tipo:
    [('Missing Link', 9), ('Power Distance', 4)]
    """
    if isinstance(x, list) and len(x) > 0:
        return x[0][1]
    return None

df_issue_diagnosis = df_issue_adaptive.copy()

# -----------------------------
# 1. Extraer elementos dominantes
# -----------------------------
df_issue_diagnosis["dominant_macrocause"] = (
    df_issue_diagnosis["dominant_macrocauses"].apply(get_top_name)
)

df_issue_diagnosis["dominant_macrocause_frequency"] = (
    df_issue_diagnosis["dominant_macrocauses"].apply(get_top_value)
)

df_issue_diagnosis["dominant_microcause"] = (
    df_issue_diagnosis["dominant_microcauses"].apply(get_top_name)
)

df_issue_diagnosis["dominant_microcause_score"] = (
    df_issue_diagnosis["dominant_microcauses"].apply(get_top_value)
)

df_issue_diagnosis["dominant_community_smell"] = (
    df_issue_diagnosis["dominant_community_smells"].apply(get_top_name)
)

df_issue_diagnosis["dominant_community_smell_frequency"] = (
    df_issue_diagnosis["dominant_community_smells"].apply(get_top_value)
)

df_issue_diagnosis["dominant_risk"] = (
    df_issue_diagnosis["dominant_risks"].apply(get_top_name)
)

df_issue_diagnosis["dominant_risk_frequency"] = (
    df_issue_diagnosis["dominant_risks"].apply(get_top_value)
)

# -----------------------------
# 2. Seleccionar columnas de diagnóstico
# -----------------------------
diagnosis_cols = [
    "issue_number",
    "social_debt_index",
    "social_debt_level",
    "comment_count",
    "dominant_macrocause",
    "dominant_macrocause_frequency",
    "dominant_microcause",
    "dominant_microcause_score",
    "dominant_community_smell",
    "dominant_community_smell_frequency",
    "dominant_risk",
    "dominant_risk_frequency"
]

adaptive_issue_diagnosis = (
    df_issue_diagnosis[diagnosis_cols]
    .sort_values("social_debt_index", ascending=False)
)

display(adaptive_issue_diagnosis.head(20))

,issue_number,social_debt_index,social_debt_level,comment_count,dominant_macrocause,dominant_macrocause_frequency,dominant_microcause,dominant_microcause_score,dominant_community_smell,dominant_community_smell_frequency,dominant_risk,dominant_risk_frequency
76,60423,1.000000,High Social Debt,76,"Technical complexity, compatibility, and syste...",40,Compatibility Constraints,11.103824,Missing Link,37,RSK-005_Documentation_Gaps_Risk,28
53,59364,0.729301,High Social Debt,47,"Technical complexity, compatibility, and syste...",25,Compatibility Constraints,7.987268,Missing Link,30,RSK-005_Documentation_Gaps_Risk,18
166,134737,0.706681,High Social Debt,41,"Technical complexity, compatibility, and syste...",25,Compatibility Constraints,4.980499,Missing Link,30,RSK-005_Documentation_Gaps_Risk,24
8,18266,0.648390,High Social Debt,42,Coordination and workflow misalignment,24,Task rework due to misalignment,4.234959,Missing Link,27,RSK-012_ReworkRisk,19
61,59699,0.622471,High Social Debt,44,"Technical complexity, compatibility, and syste...",22,Compatibility Constraints,7.025866,Missing Link,21,RSK-013_TechnicalMaintenanceRisk,13
21,19643,0.618452,High Social Debt,42,"Technical complexity, compatibility, and syste...",14,Inefficient or inadequate tools,4.364399,Missing Link,36,RSK-005_Documentation_Gaps_Risk,14
137,134251,0.597035,High Social Debt,42,"Technical complexity, compatibility, and syste...",17,Compatibility Constraints,5.247295,Missing Link,27,RSK-005_Documentation_Gaps_Risk,13
10,18408,0.539703,High Social Debt,34,Coordination and workflow misalignment,19,Restricted Information Flow,4.028321,Missing Link,22,RSK-012_ReworkRisk,12
13,18450,0.539299,High Social Debt,38,Communication and shared understanding breakdowns,16,Unclear or ambiguous communication,4.457654,Missing Link,25,RSK-010_MiscommunicationRisk,16
7,18158,0.528994,High Social Debt,39,Coordination and workflow misalignment,13,Unclear or ambiguous communication,3.475045,Missing Link,22,RSK-012_ReworkRisk,14
38,58730,0.519876,High Social Debt,28,"Technical complexity, compatibility, and syste...",21,System configuration constraints,5.756505,Missing Link,13,RSK-013_TechnicalMaintenanceRisk,12
6,18056,0.515187,High Social Debt,41,"Technical complexity, compatibility, and syste...",15,Compatibility Constraints,3.839070,Missing Link,28,RSK-012_ReworkRisk,11
58,59551,0.512822,High Social Debt,32,"Resource, tooling, access, and validation depe...",11,Inefficient or inadequate tools,4.290266,Missing Link,25,RSK-012_ReworkRisk,11
90,61503,0.506745,High Social Debt,30,Coordination and workflow misalignment,14,Inefficient or inadequate tools,3.552498,Missing Link,23,RSK-012_ReworkRisk,12
243,136027,0.504349,High Social Debt,26,Coordination and workflow misalignment,19,Task rework due to misalignment,5.692149,Missing Link,19,RSK-012_ReworkRisk,14
5,17910,0.498225,High Social Debt,33,Coordination and workflow misalignment,12,Task rework due to misalignment,2.620673,Missing Link,26,RSK-012_ReworkRisk,11
92,133697,0.494482,High Social Debt,31,"Technical complexity, compatibility, and syste...",14,Compatibility Constraints,5.817564,Missing Link,15,RSK-013_TechnicalMaintenanceRisk,10
9,18361,0.484778,High Social Debt,33,Coordination and workflow misalignment,11,Task rework due to misalignment,3.127072,Missing Link,21,RSK-012_ReworkRisk,12
68,60016,0.479064,High Social Debt,25,"Technical complexity, compatibility, and syste...",17,Compatibility Constraints,5.451123,Missing Link,13,RSK-005_Documentation_Gaps_Risk,10
157,134624,0.474378,High Social Debt,23,Coordination and workflow misalignment,13,Task rework due to misalignment,3.439808,Missing Link,18,RSK-012_ReworkRisk,14

In [ ]:
# ============================================================
# PASO 32. DIAGNÓSTICO ADAPTATIVO EN COLUMNAS INDIVIDUALES
# Top-3 macrocausas, microcausas, smells y riesgos
# ============================================================

def extract_item_name(x, position):
    """
    Extrae el nombre del elemento en una posición específica.
    position = 0 para el primero, 1 para el segundo, 2 para el tercero.
    """
    if isinstance(x, list) and len(x) > position:
        return x[position][0]
    return None

def extract_item_value(x, position):
    """
    Extrae el valor del elemento en una posición específica.
    """
    if isinstance(x, list) and len(x) > position:
        return x[position][1]
    return None

df_issue_diagnosis_expanded = df_issue_adaptive.copy()

# -----------------------------
# 1. Macrocausas top-3
# -----------------------------
for i in range(3):
    df_issue_diagnosis_expanded[f"macrocause_{i+1}"] = (
        df_issue_diagnosis_expanded["dominant_macrocauses"]
        .apply(lambda x: extract_item_name(x, i))
    )
    df_issue_diagnosis_expanded[f"macrocause_{i+1}_frequency"] = (
        df_issue_diagnosis_expanded["dominant_macrocauses"]
        .apply(lambda x: extract_item_value(x, i))
    )

# -----------------------------
# 2. Microcausas top-3
# -----------------------------
for i in range(3):
    df_issue_diagnosis_expanded[f"microcause_{i+1}"] = (
        df_issue_diagnosis_expanded["dominant_microcauses"]
        .apply(lambda x: extract_item_name(x, i))
    )
    df_issue_diagnosis_expanded[f"microcause_{i+1}_score"] = (
        df_issue_diagnosis_expanded["dominant_microcauses"]
        .apply(lambda x: extract_item_value(x, i))
    )

# -----------------------------
# 3. Community smells top-3
# -----------------------------
for i in range(3):
    df_issue_diagnosis_expanded[f"community_smell_{i+1}"] = (
        df_issue_diagnosis_expanded["dominant_community_smells"]
        .apply(lambda x: extract_item_name(x, i))
    )
    df_issue_diagnosis_expanded[f"community_smell_{i+1}_frequency"] = (
        df_issue_diagnosis_expanded["dominant_community_smells"]
        .apply(lambda x: extract_item_value(x, i))
    )

# -----------------------------
# 4. Riesgos top-3
# -----------------------------
for i in range(3):
    df_issue_diagnosis_expanded[f"risk_{i+1}"] = (
        df_issue_diagnosis_expanded["dominant_risks"]
        .apply(lambda x: extract_item_name(x, i))
    )
    df_issue_diagnosis_expanded[f"risk_{i+1}_frequency"] = (
        df_issue_diagnosis_expanded["dominant_risks"]
        .apply(lambda x: extract_item_value(x, i))
    )

# -----------------------------
# 5. Seleccionar columnas finales de diagnóstico
# -----------------------------
expanded_diagnosis_cols = [
    "issue_number",
    "social_debt_index",
    "social_debt_level",
    "comment_count",

    "macrocause_1",
    "macrocause_1_frequency",
    "macrocause_2",
    "macrocause_2_frequency",
    "macrocause_3",
    "macrocause_3_frequency",

    "microcause_1",
    "microcause_1_score",
    "microcause_2",
    "microcause_2_score",
    "microcause_3",
    "microcause_3_score",

    "community_smell_1",
    "community_smell_1_frequency",
    "community_smell_2",
    "community_smell_2_frequency",
    "community_smell_3",
    "community_smell_3_frequency",

    "risk_1",
    "risk_1_frequency",
    "risk_2",
    "risk_2_frequency",
    "risk_3",
    "risk_3_frequency"
]

adaptive_issue_diagnosis_expanded = (
    df_issue_diagnosis_expanded[expanded_diagnosis_cols]
    .sort_values("social_debt_index", ascending=False)
)

display(adaptive_issue_diagnosis_expanded.head(20))

,issue_number,social_debt_index,social_debt_level,comment_count,macrocause_1,macrocause_1_frequency,macrocause_2,macrocause_2_frequency,macrocause_3,macrocause_3_frequency,...,community_smell_2,community_smell_2_frequency,community_smell_3,community_smell_3_frequency,risk_1,risk_1_frequency,risk_2,risk_2_frequency,risk_3,risk_3_frequency
76,60423,1.000000,High Social Debt,76,"Technical complexity, compatibility, and syste...",40,Communication and shared understanding breakdowns,15.0,Organizational and procedural workflow constra...,6.0,...,Socio-Technical Congruence Gap,17.0,Power Distance,11.0,RSK-005_Documentation_Gaps_Risk,28,RSK-013_TechnicalMaintenanceRisk,18.0,RSK-021_BackwardCompatibilityRisk,14.0
53,59364,0.729301,High Social Debt,47,"Technical complexity, compatibility, and syste...",25,"Resource, tooling, access, and validation depe...",9.0,Communication and shared understanding breakdowns,6.0,...,Socio-Technical Congruence Gap,15.0,Organizational Silo,7.0,RSK-005_Documentation_Gaps_Risk,18,RSK-012_ReworkRisk,8.0,RSK-013_TechnicalMaintenanceRisk,8.0
166,134737,0.706681,High Social Debt,41,"Technical complexity, compatibility, and syste...",25,Coordination and workflow misalignment,8.0,Organizational and procedural workflow constra...,2.0,...,Power Distance,7.0,Socio-Technical Congruence Gap,6.0,RSK-005_Documentation_Gaps_Risk,24,RSK-013_TechnicalMaintenanceRisk,4.0,RSK-021_BackwardCompatibilityRisk,4.0
8,18266,0.648390,High Social Debt,42,Coordination and workflow misalignment,24,Collaboration and interpersonal tensions,6.0,Communication and shared understanding breakdowns,5.0,...,Socio-Technical Congruence Gap,14.0,Power Distance,13.0,RSK-012_ReworkRisk,19,RSK-003_Collaboration_Breakdown_Risk,5.0,RSK-010_MiscommunicationRisk,4.0
61,59699,0.622471,High Social Debt,44,"Technical complexity, compatibility, and syste...",22,Communication and shared understanding breakdowns,13.0,Collaboration and interpersonal tensions,4.0,...,Socio-Technical Congruence Gap,15.0,Power Distance,5.0,RSK-013_TechnicalMaintenanceRisk,13,RSK-021_BackwardCompatibilityRisk,12.0,RSK-005_Documentation_Gaps_Risk,10.0
21,19643,0.618452,High Social Debt,42,"Technical complexity, compatibility, and syste...",14,"Resource, tooling, access, and validation depe...",12.0,Coordination and workflow misalignment,7.0,...,Truck Factor,11.0,Organizational Silo,5.0,RSK-005_Documentation_Gaps_Risk,14,RSK-012_ReworkRisk,10.0,RSK-010_MiscommunicationRisk,5.0
137,134251,0.597035,High Social Debt,42,"Technical complexity, compatibility, and syste...",17,Coordination and workflow misalignment,12.0,Communication and shared understanding breakdowns,6.0,...,Socio-Technical Congruence Gap,11.0,Power Distance,9.0,RSK-005_Documentation_Gaps_Risk,13,RSK-012_ReworkRisk,12.0,RSK-013_TechnicalMaintenanceRisk,6.0
10,18408,0.539703,High Social Debt,34,Coordination and workflow misalignment,19,"Technical complexity, compatibility, and syste...",7.0,Communication and shared understanding breakdowns,5.0,...,Power Distance,11.0,Organizational Silo,9.0,RSK-012_ReworkRisk,12,RSK-005_Documentation_Gaps_Risk,9.0,RSK-003_Collaboration_Breakdown_Risk,6.0
13,18450,0.539299,High Social Debt,38,Communication and shared understanding breakdowns,16,"Technical complexity, compatibility, and syste...",9.0,"Knowledge, documentation, and standards defici...",7.0,...,Power Distance,17.0,Socio-Technical Congruence Gap,7.0,RSK-010_MiscommunicationRisk,16,RSK-020_MisinterpretationRisk,15.0,RSK-013_TechnicalMaintenanceRisk,11.0
7,18158,0.528994,High Social Debt,39,Coordination and workflow misalignment,13,Communication and shared understanding breakdowns,13.0,"Knowledge, documentation, and standards defici...",8.0,...,Power Distance,11.0,Truck Factor,10.0,RSK-012_ReworkRisk,14,RSK-013_TechnicalMaintenanceRisk,8.0,RSK-011_KnowledgeLossRisk,7.0
38,58730,0.519876,High Social Debt,28,"Technical complexity, compatibility, and syste...",21,Coordination and workflow misalignment,3.0,"Resource, tooling, access, and validation depe...",2.0,...,Socio-Technical Congruence Gap,13.0,Truck Factor,7.0,RSK-013_TechnicalMaintenanceRisk,12,RSK-005_Documentation_Gaps_Risk,10.0,RSK-021_BackwardCompatibilityRisk,5.0
6,18056,0.515187,High Social Debt,41,"Technical complexity, compatibility, and syste...",15,Coordination and workflow misalignment,12.0,Communication and shared understanding breakdowns,9.0,...,Socio-Technical Congruence Gap,12.0,Organizational Silo,8.0,RSK-012_ReworkRisk,11,RSK-013_TechnicalMaintenanceRisk,9.0,RSK-005_Documentation_Gaps_Risk,8.0
58,59551,0.512822,High Social Debt,32,"Resource, tooling, access, and validation depe...",11,Coordination and workflow misalignment,10.0,Communication and shared understanding breakdowns,5.0,...,Organizational Silo,12.0,Power Distance,6.0,RSK-012_ReworkRisk,11,RSK-005_Documentation_Gaps_Risk,4.0,RSK-025_AccessBottleneckRisk,4.0
90,61503,0.506745,High Social Debt,30,Coordination and workflow misalignment,14,"Resource, tooling, access, and validation depe...",9.0,Communication and shared understanding breakdowns,5.0,...,Socio-Technical Congruence Gap,10.0,Organizational Silo,8.0,RSK-012_ReworkRisk,12,RSK-025_AccessBottleneckRisk,5.0,RSK-003_Collaboration_Breakdown_Risk,3.0
243,136027,0.504349,High Social Debt,26,Coordination and workflow misalignment,19,"Technical complexity, compatibility, and syste...",3.0,Organizational and procedural workflow constra...,2.0,...,Socio-Technical Congruence Gap,11.0,Organizational Silo,5.0,RSK-012_ReworkRisk,14,RSK-003_Collaboration_Breakdown_Risk,3.0,RSK-003_Feedback_Delays_Risk,2.0
5,17910,0.498225,High Social Debt,33,Coordination and workflow misalignment,12,Communication and shared understanding breakdowns,9.0,"Technical complexity, compatibility, and syste...",8.0,...,Socio-Technical Congruence Gap,9.0,Power Distance,8.0,RSK-012_ReworkRisk,11,RSK-005_Documentation_Gaps_Risk,8.0,RSK-010_MiscommunicationRisk,7.0
92,133697,0.494482,High Social Debt,31,"Technical complexity, compatibility, and syste...",14,Communication and shared understanding breakdowns,6.0,Coordination and workflow misalignment,5.0,...,Socio-Technical Congruence Gap,8.0,Power Distance,7.0,RSK-013_TechnicalMaintenanceRisk,10,RSK-021_BackwardCompatibilityRisk,7.0,RSK-005_Documentation_Gaps_Risk,6.0
9,18361,0.484778,High Social Debt,33,Coordination and workflow misalignment,11,"Technical complexity, compatibility, and syste...",10.0,"Resource, tooling, access, and validation depe...",7.0,...,Socio-Technical Congruence Gap,16.0,Organizational Silo,6.0,RSK-012_ReworkRisk,12,RSK-005_Documentation_Gaps_Risk,7.0,RSK-013_TechnicalMaintenanceRisk,5.0
68,60016,0.479064,High Social Debt,25,"Technical complexity, compatibility, and syste...",17,Coordination and workflow misalignment,4.0,"Knowledge, documentation, and standards defici...",2.0,...,Socio-Technical Congruence Gap,7.0,Organizational Silo,3.0,RSK-005_Documentation_Gaps_Risk,10,RSK-013_TechnicalMaintenanceRisk,9.0,RSK-021_BackwardCompatibilityRisk,7.0
157,134624,0.474378,High Social Debt,23,Coordination and workflow misalignment,13,Communication and shared understanding breakdowns,6.0,Organizational and procedural workflow constra...,2.0,...,Organizational Silo,8.0,Power Distance,6.0,RSK-012_ReworkRisk,14,RSK-004_Language_Miscommunication_Risk,3.0,RSK-010_MiscommunicationRisk,3.0

In [ ]:
display(
    adaptive_issue_diagnosis_expanded[
        [
            "issue_number",
            "social_debt_index",
            "social_debt_level",
            "microcause_1",
            "microcause_1_score",
            "microcause_2",
            "microcause_2_score",
            "microcause_3",
            "microcause_3_score"
        ]
    ].head(20)
)

,issue_number,social_debt_index,social_debt_level,microcause_1,microcause_1_score,microcause_2,microcause_2_score,microcause_3,microcause_3_score
76,60423,1.000000,High Social Debt,Compatibility Constraints,11.103824,System configuration constraints,6.758318,Technical complexity due to dependencies,4.272031
53,59364,0.729301,High Social Debt,Compatibility Constraints,7.987268,System configuration constraints,5.273999,Technical complexity due to dependencies,3.368436
166,134737,0.706681,High Social Debt,Compatibility Constraints,4.980499,System configuration constraints,4.104827,Lack of Interface Clarification,2.392531
8,18266,0.648390,High Social Debt,Task rework due to misalignment,4.234959,Coordination misalignment for technical valida...,4.068062,Lack of Task Discussion,1.165648
61,59699,0.622471,High Social Debt,Compatibility Constraints,7.025866,Lack of Interface Clarification,3.532959,Technical complexity due to dependencies,2.453394
21,19643,0.618452,High Social Debt,Inefficient or inadequate tools,4.364399,System configuration constraints,2.092901,Compatibility Constraints,1.980649
137,134251,0.597035,High Social Debt,Compatibility Constraints,5.247295,System configuration constraints,2.792821,Task rework due to misalignment,2.142151
10,18408,0.539703,High Social Debt,Restricted Information Flow,4.028321,Task rework due to misalignment,3.854836,Coordination misalignment for technical valida...,2.984083
13,18450,0.539299,High Social Debt,Unclear or ambiguous communication,4.457654,Compatibility Constraints,1.822552,Lack of technical documentation,1.417502
7,18158,0.528994,High Social Debt,Unclear or ambiguous communication,3.475045,Restricted Information Flow,1.449993,Lack of technical documentation,1.395973
38,58730,0.519876,High Social Debt,System configuration constraints,5.756505,Compatibility Constraints,5.343550,Technical complexity due to dependencies,4.433127
6,18056,0.515187,High Social Debt,Compatibility Constraints,3.839070,Unclear or ambiguous communication,2.140463,Task rework due to misalignment,2.077273
58,59551,0.512822,High Social Debt,Inefficient or inadequate tools,4.290266,Coordination misalignment for technical valida...,2.452418,Request for Technical Validation Support,1.643487
90,61503,0.506745,High Social Debt,Inefficient or inadequate tools,3.552498,Task rework due to misalignment,2.848520,Coordination misalignment for technical valida...,2.605615
243,136027,0.504349,High Social Debt,Task rework due to misalignment,5.692149,Coordination misalignment for technical valida...,2.807625,Restricted Information Flow,2.807334
5,17910,0.498225,High Social Debt,Task rework due to misalignment,2.620673,Coordination misalignment for technical valida...,2.549162,Unclear or ambiguous communication,2.018487
92,133697,0.494482,High Social Debt,Compatibility Constraints,5.817564,System configuration constraints,4.606674,Technical complexity due to dependencies,2.768502
9,18361,0.484778,High Social Debt,Task rework due to misalignment,3.127072,Compatibility Constraints,2.866266,Inefficient or inadequate tools,2.560302
68,60016,0.479064,High Social Debt,Compatibility Constraints,5.451123,Lack of Interface Clarification,2.893063,Preservation of prior system behavior,1.319744
157,134624,0.474378,High Social Debt,Task rework due to misalignment,3.439808,Coordination misalignment for technical valida...,3.339630,Restricted Information Flow,1.884372

In [ ]:
# ============================================================
# PASO 33. VERIFICAR COLUMNAS DE ESTRATEGIAS EN EL DATASET
# ============================================================

strategy_cols = [
    col for col in df.columns
    if "strateg" in col.lower()
]

print(strategy_cols)

display(
    df[
        [
            "issue_number",
            "primary_microcause_name",
            "preventive_strategies",
            "corrective_strategies"
        ]
    ].head(10)
)

['preventive_strategies', 'corrective_strategies']

,issue_number,primary_microcause_name,preventive_strategies,corrective_strategies
0,291739,Lack of Interface Clarification,• PS-021_CompatibilityImpactAnalysis\n• PS-026...,• CS-021_TargetedCompatibilityValidation
1,291739,Lack of Interface Clarification,• PS-004_InterfaceClarificationWorkshops\n• PS...,• CS-034_ResourceUseCorrection\n• STR-I-015_Ch...
2,291739,Lack of Interface Clarification,• PS-004_InterfaceClarificationWorkshops\n• PS...,• CS-034_ResourceUseCorrection\n• STR-I-015_Ch...
3,291739,Lack of Interface Clarification,• PS-004_InterfaceClarificationWorkshops\n• PS...,• CS-034_ResourceUseCorrection\n• STR-I-015_Ch...
4,291739,Unclear or ambiguous communication,• PS-017_TimelyFeedbackMechanism\n• PS-104_Com...,• CS-020_RestateAndClarifyMeaning\n• STR-G-003...
5,291739,Delayed Communication,• PS-017_TimelyFeedbackMechanism\n• PS-104_Com...,• CS-020_RestateAndClarifyMeaning\n• STR-G-003...
6,291739,System configuration constraints,• PS-004_InterfaceClarificationWorkshops\n• PS...,• CS-034_ResourceUseCorrection\n• STR-I-015_Ch...
7,291739,Lack of Interface Clarification,• PS-004_InterfaceClarificationWorkshops\n• PS...,• CS-034_ResourceUseCorrection\n• STR-I-015_Ch...
8,291739,Lack of Interface Clarification,• PS-004_InterfaceClarificationWorkshops\n• PS...,• CS-034_ResourceUseCorrection\n• STR-I-015_Ch...
9,291739,Unclear or ambiguous communication,• PS-003_TransparentInformationChannels\n• PS-...,• CS-020_RestateAndClarifyMeaning\n• CS-020_Sh...

In [ ]:
# ============================================================
# PASO 34. AGREGAR ESTRATEGIAS PREVENTIVAS Y CORRECTIVAS POR ISSUE
# ============================================================

from collections import Counter
import pandas as pd

def parse_strategy_cell(value):
    """
    Convierte una celda tipo:
    • PS-004_InterfaceClarificationWorkshops
    • PS-017_TimelyFeedbackMechanism

    en una lista:
    ['PS-004_InterfaceClarificationWorkshops', 'PS-017_TimelyFeedbackMechanism']
    """
    if pd.isna(value):
        return []

    items = []
    for line in str(value).split("\n"):
        line = line.strip()
        line = line.replace("•", "").strip()
        if line:
            items.append(line)
    return items


# -----------------------------
# 1. Parsear estrategias
# -----------------------------
df["preventive_strategies_list"] = (
    df["preventive_strategies"]
    .apply(parse_strategy_cell)
)

df["corrective_strategies_list"] = (
    df["corrective_strategies"]
    .apply(parse_strategy_cell)
)


# -----------------------------
# 2. Agregar estrategias por issue
# -----------------------------
strategy_rows = []

for issue_number, group in df.groupby("issue_number"):

    preventive_counter = Counter()
    corrective_counter = Counter()

    for _, row in group.iterrows():

        for strategy in row["preventive_strategies_list"]:
            preventive_counter[strategy] += 1

        for strategy in row["corrective_strategies_list"]:
            corrective_counter[strategy] += 1

    strategy_rows.append({
        "issue_number": issue_number,
        "top_preventive_strategies": preventive_counter.most_common(3),
        "top_corrective_strategies": corrective_counter.most_common(3)
    })

issue_strategies = pd.DataFrame(strategy_rows)

display(issue_strategies.head(10))

,issue_number,top_preventive_strategies,top_corrective_strategies
0,17660,"[(PS-023_CoordinationProtocols, 8), (PS-026_Co...","[(CS-034_ResourceUseCorrection, 5), (CS-028_Ta..."
1,17675,"[(PS-023_CoordinationProtocols, 10), (PS-004_I...","[(CS-034_ResourceUseCorrection, 14), (CS-027_T..."
2,17690,"[(PS-023_CoordinationProtocols, 6), (PS-024_Al...","[(CS-028_TaskDeliveryRecoveryPlan, 8), (CS-029..."
3,17806,"[(PS-027_TechnicalDocumentationPractices, 6), ...","[(CS-034_ResourceUseCorrection, 8), (CS-028_Ta..."
4,17809,"[(PS-023_CoordinationProtocols, 7), (PS-026_Co...","[(CS-034_ResourceUseCorrection, 9), (CS-027_Ta..."
5,17910,"[(PS-023_CoordinationProtocols, 12), (PS-026_C...","[(CS-034_ResourceUseCorrection, 14), (CS-020_R..."
6,18056,"[(PS-026_CompatibilityManagement, 12), (PS-023...","[(CS-034_ResourceUseCorrection, 13), (CS-028_T..."
7,18158,"[(PS-023_CoordinationProtocols, 11), (PS-016_C...","[(CS-028_TaskDeliveryRecoveryPlan, 16), (CS-02..."
8,18266,"[(PS-023_CoordinationProtocols, 22), (PS-024_A...","[(CS-034_ResourceUseCorrection, 13), (CS-028_T..."
9,18361,"[(PS-023_CoordinationProtocols, 11), (PS-026_C...","[(CS-034_ResourceUseCorrection, 15), (CS-027_T..."

In [ ]:
# ============================================================
# PASO 35. UNIR DIAGNÓSTICO ADAPTATIVO CON ESTRATEGIAS
# ============================================================

adaptive_issue_diagnosis_final = adaptive_issue_diagnosis_expanded.merge(
    issue_strategies,
    on="issue_number",
    how="left"
)

display(
    adaptive_issue_diagnosis_final
    .sort_values("social_debt_index", ascending=False)
    .head(20)
)

print("Dimensiones diagnóstico final:", adaptive_issue_diagnosis_final.shape)

,issue_number,social_debt_index,social_debt_level,comment_count,macrocause_1,macrocause_1_frequency,macrocause_2,macrocause_2_frequency,macrocause_3,macrocause_3_frequency,...,community_smell_3,community_smell_3_frequency,risk_1,risk_1_frequency,risk_2,risk_2_frequency,risk_3,risk_3_frequency,top_preventive_strategies,top_corrective_strategies
0,60423,1.000000,High Social Debt,76,"Technical complexity, compatibility, and syste...",40,Communication and shared understanding breakdowns,15.0,Organizational and procedural workflow constra...,6.0,...,Power Distance,11.0,RSK-005_Documentation_Gaps_Risk,28,RSK-013_TechnicalMaintenanceRisk,18.0,RSK-021_BackwardCompatibilityRisk,14.0,"[(PS-026_CompatibilityManagement, 38), (PS-027...","[(CS-034_ResourceUseCorrection, 27), (STR-I-01..."
1,59364,0.729301,High Social Debt,47,"Technical complexity, compatibility, and syste...",25,"Resource, tooling, access, and validation depe...",9.0,Communication and shared understanding breakdowns,6.0,...,Organizational Silo,7.0,RSK-005_Documentation_Gaps_Risk,18,RSK-012_ReworkRisk,8.0,RSK-013_TechnicalMaintenanceRisk,8.0,"[(PS-026_CompatibilityManagement, 24), (PS-004...","[(CS-034_ResourceUseCorrection, 21), (STR-I-01..."
2,134737,0.706681,High Social Debt,41,"Technical complexity, compatibility, and syste...",25,Coordination and workflow misalignment,8.0,Organizational and procedural workflow constra...,2.0,...,Socio-Technical Congruence Gap,6.0,RSK-005_Documentation_Gaps_Risk,24,RSK-013_TechnicalMaintenanceRisk,4.0,RSK-021_BackwardCompatibilityRisk,4.0,"[(PS-026_CompatibilityManagement, 25), (PS-004...","[(CS-034_ResourceUseCorrection, 23), (STR-I-01..."
3,18266,0.648390,High Social Debt,42,Coordination and workflow misalignment,24,Collaboration and interpersonal tensions,6.0,Communication and shared understanding breakdowns,5.0,...,Power Distance,13.0,RSK-012_ReworkRisk,19,RSK-003_Collaboration_Breakdown_Risk,5.0,RSK-010_MiscommunicationRisk,4.0,"[(PS-023_CoordinationProtocols, 22), (PS-024_A...","[(CS-034_ResourceUseCorrection, 13), (CS-028_T..."
4,59699,0.622471,High Social Debt,44,"Technical complexity, compatibility, and syste...",22,Communication and shared understanding breakdowns,13.0,Collaboration and interpersonal tensions,4.0,...,Power Distance,5.0,RSK-013_TechnicalMaintenanceRisk,13,RSK-021_BackwardCompatibilityRisk,12.0,RSK-005_Documentation_Gaps_Risk,10.0,"[(PS-026_CompatibilityManagement, 20), (PS-021...","[(CS-020_RestateAndClarifyMeaning, 15), (CS-02..."
5,19643,0.618452,High Social Debt,42,"Technical complexity, compatibility, and syste...",14,"Resource, tooling, access, and validation depe...",12.0,Coordination and workflow misalignment,7.0,...,Organizational Silo,5.0,RSK-005_Documentation_Gaps_Risk,14,RSK-012_ReworkRisk,10.0,RSK-010_MiscommunicationRisk,5.0,"[(PS-027_TechnicalDocumentationPractices, 16),...","[(CS-034_ResourceUseCorrection, 18), (STR-I-01..."
6,134251,0.597035,High Social Debt,42,"Technical complexity, compatibility, and syste...",17,Coordination and workflow misalignment,12.0,Communication and shared understanding breakdowns,6.0,...,Power Distance,9.0,RSK-005_Documentation_Gaps_Risk,13,RSK-012_ReworkRisk,12.0,RSK-013_TechnicalMaintenanceRisk,6.0,"[(PS-026_CompatibilityManagement, 17), (PS-027...","[(CS-034_ResourceUseCorrection, 18), (STR-I-01..."
7,18408,0.539703,High Social Debt,34,Coordination and workflow misalignment,19,"Technical complexity, compatibility, and syste...",7.0,Communication and shared understanding breakdowns,5.0,...,Organizational Silo,9.0,RSK-012_ReworkRisk,12,RSK-005_Documentation_Gaps_Risk,9.0,RSK-003_Collaboration_Breakdown_Risk,6.0,"[(PS-023_CoordinationProtocols, 15), (PS-005_C...","[(CS-028_TaskDeliveryRecoveryPlan, 13), (CS-03..."
8,18450,0.539299,High Social Debt,38,Communication and shared understanding breakdowns,16,"Technical complexity, compatibility, and syste...",9.0,"Knowledge, documentation, and standards defici...",7.0,...,Socio-Technical Congruence Gap,7.0,RSK-010_MiscommunicationRisk,16,RSK-020_MisinterpretationRisk,15.0,RSK-013_TechnicalMaintenanceRisk,11.0,"[(PS-016_ClearCommunicationGuidelines, 16), (P...","[(CS-028_TaskDeliveryRecoveryPlan, 18), (CS-02..."
9,18158,0.528994,High Social Debt,39,Coordination and workflow misalignment,13,Communication and shared understanding breakdowns,13.0,"Knowledge, documentation, and standards defici...",8.0,...,Truck Factor,10.0,RSK-012_ReworkRisk,14,RSK-013_TechnicalMaintenanceRisk,8.0,RSK-011_KnowledgeLossRisk,7.0,"[(PS-023_CoordinationProtocols, 11), (PS-016_C...","[(CS-028_TaskDeliveryRecoveryPlan, 16), (CS-02..."
10,58730,0.519876,High Social Debt,28,"Technical complexity, compatibility, and syste...",21,Coordination and workflow misalignment,3.0,"Resource, tooling, access, and validation depe...",2.0,...,Truck Factor,7.0,RSK-013_TechnicalMaintenanceRisk,12,RSK-005_Documentation_Gaps_Risk,10.0,RSK-021_BackwardCompatibilityRisk,5.0,"[(PS-026_CompatibilityManagement, 15), (PS-027...","[(CS-034_ResourceUseCorrection, 10), (STR-I-01..."
11,18056,0.515187,High Social Debt,41,"Technical complexity, compatibility, and syste...",15,Coordination and workflow misalignment,12.0,Communication and shared understanding breakdowns,9.0,...,Organizational Silo,8.0,RSK-012_ReworkRisk,11,RSK-013_TechnicalMaintenanceRisk,9.0,RSK-005_Documentation_Gaps_Risk,8.0,"[(PS-026_CompatibilityManagement, 12), (PS-023...","[(CS-034_ResourceUseCorrection, 13), (CS-028_T..."
12,59551,0.512822,High Social Debt,32,"Resource, tooling, access, and validation depe...",11,Coordination and workflow misalignment,10.0,Communication and shared understanding breakdowns,5.0,...,Power Distance,6.0,RSK-012_ReworkRisk,11,RSK-005_Documentation_Gaps_Risk,4.0,RSK-025_AccessBottleneckRisk,4.0,"[(PS-024_AlignmentMeetings, 9), (PS-023_Coordi...","[(CS-028_TaskDeliveryRecoveryPlan, 13), (CS-02..."
13,61503,0.506745,High Social Debt,30,Coordination and workflow misalignment,14,"Resource, tooling, access, and validation depe...",9.0,Communication and shared understanding breakdowns,5.0,...,Organizational Silo,8.0,RSK-012_ReworkRisk,12,RSK-025_AccessBottleneckRisk,5.0,RSK-003_Collaboration_Breakdown_Risk,3.0,"[(PS-023_CoordinationProtocols, 11), (PS-025_A...","[(CS-034_ResourceUseCorrection, 10), (CS-027_T..."
14,136027,0.504349,High Social Debt,26,Coordination and workflow misalignment,19,"Technical complexity, compatibility, and syste...",3.0,Organizational and procedural workflow constra...,2.0,...,Organizational Silo,5.0,RSK-012_ReworkRisk,14,RSK-003_Collaboration_Breakdown_Risk,3.0,RSK-003_Feedback_Delays_Risk,2.0,"[(PS-023_CoordinationProtocols, 17), (PS-005_C...","[(CS-034_ResourceUseCorrection, 12), (CS-027_T..."
15,17910,0.498225,High Social Debt,33,Coordination and workflow misalignment,12,Communication and shared understanding breakdowns,9.0,"Technical complexity, compatibility, and syste...",8.0,...,Power Distance,8.0,RSK-012_ReworkRisk,11,RSK-005_Documentation_Gaps_Risk,8.0,RSK-010_MiscommunicationRisk,7.0,"[(PS-023_CoordinationProtocols, 12), (PS-026_C...","[(CS-034_ResourceUseCorrection, 14), (CS-020_R..."
16,133697,0.494482,High Social Debt,31,"Technical complexity, compatibility, and syste...",14,Communication and shared understanding breakdowns,6.0,Coordination and workflow misalignment,5.0,...,Power Distance,7.0,RSK-013_TechnicalMaintenanceRisk,10,RSK-021_BackwardCompatibilityRisk,7.0,RSK-005_Documentation_Gaps_Risk,6.0,"[(PS-026_CompatibilityManagement, 13), (PS-027...","[(CS-028_TaskDeliveryRecoveryPlan, 8), (CS-021..."
17,18361,0.484778,High Social Debt,33,Coordination and workflow misalignment,11,"Technical complexity, compatibility, and syste...",10.0,"Resource, tooling, access, and validation depe...",7.0,...,Organizational Silo,6.0,RSK-012_ReworkRisk,12,RSK-005_Documentation_Gaps_Risk,7.0,RSK-013_TechnicalMaintenanceRisk,5.0,"[(PS-023_CoordinationProtocols, 11), (PS-026_C...","[(CS-034_ResourceUseCorrection, 15), (CS-027_T..."
18,60016,0.479064,High Social Debt,25,"Technical complexity, compatibility, and syste...",17,Coordination and workflow misalignment,4.0,"Knowledge, documentation, and standards defici...",2.0,...,Organizational Silo,3.0,RSK-005_Documentation_Gaps_Risk,10,RSK-013_TechnicalMaintenanceRisk,9.0,RSK-021_BackwardCompatibilityRisk,7.0,"[(PS-026_CompatibilityManagement, 15), (PS-004...","[(CS-034_ResourceUseCorrection, 8), (STR-I-015..."
19,134624,0.474378,High Social Debt,23,Coordination and workflow misalignment,13,Communication and shared understanding breakdowns,6.0,Organizational and procedural workflow constra...,2.0,...,Power Distance,6.0,RSK-012_ReworkRisk,14,RSK-004_Language_Miscommunication_Risk,3.0,RSK-010_MiscommunicationRisk,3.0,"[(PS-023_CoordinationProtocols, 13), (PS-024_A...","[(CS-028_TaskDeliveryRecoveryPlan, 11), (CS-02..."

Dimensiones diagnóstico final: (265, 30)

In [ ]:
# ============================================================
# PASO 36. EXPANDIR ESTRATEGIAS EN COLUMNAS INDIVIDUALES
# ============================================================

def extract_strategy_name(x, position):
    if isinstance(x, list) and len(x) > position:
        return x[position][0]
    return None

def extract_strategy_value(x, position):
    if isinstance(x, list) and len(x) > position:
        return x[position][1]
    return None

df_final_diagnosis_expanded = adaptive_issue_diagnosis_final.copy()

# -----------------------------
# 1. Estrategias preventivas top-3
# -----------------------------
for i in range(3):
    df_final_diagnosis_expanded[f"preventive_strategy_{i+1}"] = (
        df_final_diagnosis_expanded["top_preventive_strategies"]
        .apply(lambda x: extract_strategy_name(x, i))
    )
    df_final_diagnosis_expanded[f"preventive_strategy_{i+1}_frequency"] = (
        df_final_diagnosis_expanded["top_preventive_strategies"]
        .apply(lambda x: extract_strategy_value(x, i))
    )

# -----------------------------
# 2. Estrategias correctivas top-3
# -----------------------------
for i in range(3):
    df_final_diagnosis_expanded[f"corrective_strategy_{i+1}"] = (
        df_final_diagnosis_expanded["top_corrective_strategies"]
        .apply(lambda x: extract_strategy_name(x, i))
    )
    df_final_diagnosis_expanded[f"corrective_strategy_{i+1}_frequency"] = (
        df_final_diagnosis_expanded["top_corrective_strategies"]
        .apply(lambda x: extract_strategy_value(x, i))
    )

# -----------------------------
# 3. Eliminar columnas tipo lista si quieres una tabla limpia
# -----------------------------
df_final_diagnosis_clean = df_final_diagnosis_expanded.drop(
    columns=[
        "top_preventive_strategies",
        "top_corrective_strategies"
    ]
)

display(df_final_diagnosis_clean.head(20))

print("Dimensiones diagnóstico limpio:", df_final_diagnosis_clean.shape)

,issue_number,social_debt_index,social_debt_level,comment_count,macrocause_1,macrocause_1_frequency,macrocause_2,macrocause_2_frequency,macrocause_3,macrocause_3_frequency,...,preventive_strategy_2,preventive_strategy_2_frequency,preventive_strategy_3,preventive_strategy_3_frequency,corrective_strategy_1,corrective_strategy_1_frequency,corrective_strategy_2,corrective_strategy_2_frequency,corrective_strategy_3,corrective_strategy_3_frequency
0,60423,1.000000,High Social Debt,76,"Technical complexity, compatibility, and syste...",40,Communication and shared understanding breakdowns,15.0,Organizational and procedural workflow constra...,6.0,...,PS-027_TechnicalDocumentationPractices,28.0,PS-004_InterfaceClarificationWorkshops,26.0,CS-034_ResourceUseCorrection,27,STR-I-015_ChangeManagementTraining,24.0,STR-I-016_ChangeChampions,24.0
1,59364,0.729301,High Social Debt,47,"Technical complexity, compatibility, and syste...",25,"Resource, tooling, access, and validation depe...",9.0,Communication and shared understanding breakdowns,6.0,...,PS-004_InterfaceClarificationWorkshops,17.0,PS-012_InterfaceDocumentationGuidelines,17.0,CS-034_ResourceUseCorrection,21,STR-I-015_ChangeManagementTraining,17.0,STR-I-016_ChangeChampions,17.0
2,134737,0.706681,High Social Debt,41,"Technical complexity, compatibility, and syste...",25,Coordination and workflow misalignment,8.0,Organizational and procedural workflow constra...,2.0,...,PS-004_InterfaceClarificationWorkshops,21.0,PS-012_InterfaceDocumentationGuidelines,21.0,CS-034_ResourceUseCorrection,23,STR-I-015_ChangeManagementTraining,21.0,STR-I-016_ChangeChampions,21.0
3,18266,0.648390,High Social Debt,42,Coordination and workflow misalignment,24,Collaboration and interpersonal tensions,6.0,Communication and shared understanding breakdowns,5.0,...,PS-024_AlignmentMeetings,8.0,PS-005_CrossTeamCoordinationMeetings,5.0,CS-034_ResourceUseCorrection,13,CS-028_TaskDeliveryRecoveryPlan,12.0,CS-027_TaskConflictResolution,12.0
4,59699,0.622471,High Social Debt,44,"Technical complexity, compatibility, and syste...",22,Communication and shared understanding breakdowns,13.0,Collaboration and interpersonal tensions,4.0,...,PS-021_CompatibilityImpactAnalysis,12.0,PS-004_InterfaceClarificationWorkshops,10.0,CS-020_RestateAndClarifyMeaning,15,CS-021_TargetedCompatibilityValidation,12.0,CS-034_ResourceUseCorrection,11.0
5,19643,0.618452,High Social Debt,42,"Technical complexity, compatibility, and syste...",14,"Resource, tooling, access, and validation depe...",12.0,Coordination and workflow misalignment,7.0,...,PS-004_InterfaceClarificationWorkshops,14.0,PS-012_InterfaceDocumentationGuidelines,14.0,CS-034_ResourceUseCorrection,18,STR-I-015_ChangeManagementTraining,14.0,STR-I-016_ChangeChampions,14.0
6,134251,0.597035,High Social Debt,42,"Technical complexity, compatibility, and syste...",17,Coordination and workflow misalignment,12.0,Communication and shared understanding breakdowns,6.0,...,PS-027_TechnicalDocumentationPractices,13.0,PS-004_InterfaceClarificationWorkshops,12.0,CS-034_ResourceUseCorrection,18,STR-I-015_ChangeManagementTraining,12.0,STR-I-016_ChangeChampions,12.0
7,18408,0.539703,High Social Debt,34,Coordination and workflow misalignment,19,"Technical complexity, compatibility, and syste...",7.0,Communication and shared understanding breakdowns,5.0,...,PS-005_CrossTeamCoordinationMeetings,8.0,PS-014_SharedCoordinationCalendar,8.0,CS-028_TaskDeliveryRecoveryPlan,13,CS-034_ResourceUseCorrection,11.0,CS-029_EffortRealignmentReview,9.0
8,18450,0.539299,High Social Debt,38,Communication and shared understanding breakdowns,16,"Technical complexity, compatibility, and syste...",9.0,"Knowledge, documentation, and standards defici...",7.0,...,PS-018_InformationClarificationPractice,16.0,PS-003_TransparentInformationChannels,15.0,CS-028_TaskDeliveryRecoveryPlan,18,CS-020_RestateAndClarifyMeaning,17.0,CS-020_SharedUnderstandingRecovery,15.0
9,18158,0.528994,High Social Debt,39,Coordination and workflow misalignment,13,Communication and shared understanding breakdowns,13.0,"Knowledge, documentation, and standards defici...",8.0,...,PS-016_ClearCommunicationGuidelines,11.0,PS-018_InformationClarificationPractice,11.0,CS-028_TaskDeliveryRecoveryPlan,16,CS-029_EffortRealignmentReview,11.0,CS-PM-006_EffortAlignmentRecovery,11.0
10,58730,0.519876,High Social Debt,28,"Technical complexity, compatibility, and syste...",21,Coordination and workflow misalignment,3.0,"Resource, tooling, access, and validation depe...",2.0,...,PS-027_TechnicalDocumentationPractices,11.0,PS-004_InterfaceClarificationWorkshops,10.0,CS-034_ResourceUseCorrection,10,STR-I-015_ChangeManagementTraining,10.0,STR-I-016_ChangeChampions,10.0
11,18056,0.515187,High Social Debt,41,"Technical complexity, compatibility, and syste...",15,Coordination and workflow misalignment,12.0,Communication and shared understanding breakdowns,9.0,...,PS-023_CoordinationProtocols,11.0,PS-027_TechnicalDocumentationPractices,10.0,CS-034_ResourceUseCorrection,13,CS-028_TaskDeliveryRecoveryPlan,11.0,CS-029_EffortRealignmentReview,9.0
12,59551,0.512822,High Social Debt,32,"Resource, tooling, access, and validation depe...",11,Coordination and workflow misalignment,10.0,Communication and shared understanding breakdowns,5.0,...,PS-023_CoordinationProtocols,8.0,PS-004_InterfaceClarificationWorkshops,4.0,CS-028_TaskDeliveryRecoveryPlan,13,CS-029_EffortRealignmentReview,10.0,CS-PM-006_EffortAlignmentRecovery,10.0
13,61503,0.506745,High Social Debt,30,Coordination and workflow misalignment,14,"Resource, tooling, access, and validation depe...",9.0,Communication and shared understanding breakdowns,5.0,...,PS-025_AccessPlanning,5.0,PS-024_AlignmentMeetings,4.0,CS-034_ResourceUseCorrection,10,CS-027_TaskConflictResolution,9.0,CS-033_ReworkReductionReview,9.0
14,136027,0.504349,High Social Debt,26,Coordination and workflow misalignment,19,"Technical complexity, compatibility, and syste...",3.0,Organizational and procedural workflow constra...,2.0,...,PS-005_CrossTeamCoordinationMeetings,5.0,PS-014_SharedCoordinationCalendar,5.0,CS-034_ResourceUseCorrection,12,CS-027_TaskConflictResolution,10.0,CS-033_ReworkReductionReview,10.0
15,17910,0.498225,High Social Debt,33,Coordination and workflow misalignment,12,Communication and shared understanding breakdowns,9.0,"Technical complexity, compatibility, and syste...",8.0,...,PS-026_CompatibilityManagement,8.0,PS-027_TechnicalDocumentationPractices,8.0,CS-034_ResourceUseCorrection,14,CS-020_RestateAndClarifyMeaning,10.0,CS-028_TaskDeliveryRecoveryPlan,9.0
16,133697,0.494482,High Social Debt,31,"Technical complexity, compatibility, and syste...",14,Communication and shared understanding breakdowns,6.0,Coordination and workflow misalignment,5.0,...,PS-027_TechnicalDocumentationPractices,8.0,PS-021_CompatibilityImpactAnalysis,7.0,CS-028_TaskDeliveryRecoveryPlan,8,CS-021_TargetedCompatibilityValidation,7.0,CS-029_EffortRealignmentReview,7.0
17,18361,0.484778,High Social Debt,33,Coordination and workflow misalignment,11,"Technical complexity, compatibility, and syste...",10.0,"Resource, tooling, access, and validation depe...",7.0,...,PS-026_CompatibilityManagement,10.0,PS-027_TechnicalDocumentationPractices,7.0,CS-034_ResourceUseCorrection,15,CS-027_TaskConflictResolution,9.0,CS-033_ReworkReductionReview,9.0
18,60016,0.479064,High Social Debt,25,"Technical complexity, compatibility, and syste...",17,Coordination and workflow misalignment,4.0,"Knowledge, documentation, and standards defici...",2.0,...,PS-004_InterfaceClarificationWorkshops,10.0,PS-012_InterfaceDocumentationGuidelines,10.0,CS-034_ResourceUseCorrection,8,STR-I-015_ChangeManagementTraining,8.0,STR-I-016_ChangeChampions,8.0
19,134624,0.474378,High Social Debt,23,Coordination and workflow misalignment,13,Communication and shared understanding breakdowns,6.0,Organizational and procedural workflow constra...,2.0,...,PS-024_AlignmentMeetings,8.0,PS-016_ClearCommunicationGuidelines,6.0,CS-028_TaskDeliveryRecoveryPlan,11,CS-029_EffortRealignmentReview,10.0,CS-PM-006_EffortAlignmentRecovery,10.0

Dimensiones diagnóstico limpio: (265, 40)

In [ ]:
# ============================================================
# PASO 37. EXPORTAR DIAGNÓSTICO ADAPTATIVO FINAL
# ============================================================

output_diagnosis = "adaptive_social_debt_diagnosis_final.xlsx"

df_final_diagnosis_clean.to_excel(output_diagnosis, index=False)

print("Archivo exportado:", output_diagnosis)
print("Dimensiones:", df_final_diagnosis_clean.shape)

Archivo exportado: adaptive_social_debt_diagnosis_final.xlsx
Dimensiones: (265, 40)

In [ ]:
# ============================================================
# PASO 38. FUNCIÓN PARA CONSULTAR DIAGNÓSTICO DE UN ISSUE
# ============================================================

def diagnose_issue(issue_number, diagnosis_df=df_final_diagnosis_clean):
    """
    Consulta el diagnóstico adaptativo de un issue específico.
    Devuelve nivel de deuda social, causas, smells, riesgos y estrategias.
    """

    result = diagnosis_df[
        diagnosis_df["issue_number"] == issue_number
    ]

    if result.empty:
        print(f"No se encontró el issue {issue_number} en el diagnóstico final.")
        return None

    row = result.iloc[0]

    print("====================================================")
    print(f"DIAGNÓSTICO ADAPTATIVO DEL ISSUE {issue_number}")
    print("====================================================")

    print("\n1. Nivel de deuda social")
    print("----------------------------------------------------")
    print("Social Debt Index:", round(row["social_debt_index"], 4))
    print("Nivel:", row["social_debt_level"])
    print("Cantidad de comentarios:", row["comment_count"])

    print("\n2. Macrocausas principales")
    print("----------------------------------------------------")
    for i in range(1, 4):
        cause = row.get(f"macrocause_{i}")
        freq = row.get(f"macrocause_{i}_frequency")
        if pd.notna(cause):
            print(f"{i}. {cause} ({freq})")

    print("\n3. Microcausas principales")
    print("----------------------------------------------------")
    for i in range(1, 4):
        cause = row.get(f"microcause_{i}")
        score = row.get(f"microcause_{i}_score")
        if pd.notna(cause):
            print(f"{i}. {cause} (score acumulado: {round(score, 3)})")

    print("\n4. Community smells principales")
    print("----------------------------------------------------")
    for i in range(1, 4):
        smell = row.get(f"community_smell_{i}")
        freq = row.get(f"community_smell_{i}_frequency")
        if pd.notna(smell):
            print(f"{i}. {smell} ({freq})")

    print("\n5. Riesgos principales")
    print("----------------------------------------------------")
    for i in range(1, 4):
        risk = row.get(f"risk_{i}")
        freq = row.get(f"risk_{i}_frequency")
        if pd.notna(risk):
            print(f"{i}. {risk} ({freq})")

    print("\n6. Estrategias preventivas recomendadas")
    print("----------------------------------------------------")
    for i in range(1, 4):
        strategy = row.get(f"preventive_strategy_{i}")
        freq = row.get(f"preventive_strategy_{i}_frequency")
        if pd.notna(strategy):
            print(f"{i}. {strategy} ({freq})")

    print("\n7. Estrategias correctivas recomendadas")
    print("----------------------------------------------------")
    for i in range(1, 4):
        strategy = row.get(f"corrective_strategy_{i}")
        freq = row.get(f"corrective_strategy_{i}_frequency")
        if pd.notna(strategy):
            print(f"{i}. {strategy} ({freq})")

    return row

In [ ]:
diagnose_issue(60423)

====================================================
DIAGNÓSTICO ADAPTATIVO DEL ISSUE 60423
====================================================

1. Nivel de deuda social
----------------------------------------------------
Social Debt Index: 1.0
Nivel: High Social Debt
Cantidad de comentarios: 76

2. Macrocausas principales
----------------------------------------------------
1. Technical complexity, compatibility, and system constraints (40)
2. Communication and shared understanding breakdowns (15.0)
3. Organizational and procedural workflow constraints (6.0)

3. Microcausas principales
----------------------------------------------------
1. Compatibility Constraints (score acumulado: 11.104)
2. System configuration constraints (score acumulado: 6.758)
3. Technical complexity due to dependencies (score acumulado: 4.272)

4. Community smells principales
----------------------------------------------------
1. Missing Link (37)
2. Socio-Technical Congruence Gap (17.0)
3. Power Distance (11.0)

5. Riesgos principales
----------------------------------------------------
1. RSK-005_Documentation_Gaps_Risk (28)
2. RSK-013_TechnicalMaintenanceRisk (18.0)
3. RSK-021_BackwardCompatibilityRisk (14.0)

6. Estrategias preventivas recomendadas
----------------------------------------------------
1. PS-026_CompatibilityManagement (38)
2. PS-027_TechnicalDocumentationPractices (28.0)
3. PS-004_InterfaceClarificationWorkshops (26.0)

7. Estrategias correctivas recomendadas
----------------------------------------------------
1. CS-034_ResourceUseCorrection (27)
2. STR-I-015_ChangeManagementTraining (24.0)
3. STR-I-016_ChangeChampions (24.0)

issue_number                                                                   60423
social_debt_index                                                                1.0
social_debt_level                                                   High Social Debt
comment_count                                                                     76
macrocause_1                       Technical complexity, compatibility, and syste...
macrocause_1_frequency                                                            40
macrocause_2                       Communication and shared understanding breakdowns
macrocause_2_frequency                                                          15.0
macrocause_3                       Organizational and procedural workflow constra...
macrocause_3_frequency                                                           6.0
microcause_1                                               Compatibility Constraints
microcause_1_score                                                         11.103824
microcause_2                                        System configuration constraints
microcause_2_score                                                          6.758318
microcause_3                                Technical complexity due to dependencies
microcause_3_score                                                          4.272031
community_smell_1                                                       Missing Link
community_smell_1_frequency                                                       37
community_smell_2                                     Socio-Technical Congruence Gap
community_smell_2_frequency                                                     17.0
community_smell_3                                                     Power Distance
community_smell_3_frequency                                                     11.0
risk_1                                               RSK-005_Documentation_Gaps_Risk
risk_1_frequency                                                                  28
risk_2                                              RSK-013_TechnicalMaintenanceRisk
risk_2_frequency                                                                18.0
risk_3                                             RSK-021_BackwardCompatibilityRisk
risk_3_frequency                                                                14.0
preventive_strategy_1                                 PS-026_CompatibilityManagement
preventive_strategy_1_frequency                                                   38
preventive_strategy_2                         PS-027_TechnicalDocumentationPractices
preventive_strategy_2_frequency                                                 28.0
preventive_strategy_3                         PS-004_InterfaceClarificationWorkshops
preventive_strategy_3_frequency                                                 26.0
corrective_strategy_1                                   CS-034_ResourceUseCorrection
corrective_strategy_1_frequency                                                   27
corrective_strategy_2                             STR-I-015_ChangeManagementTraining
corrective_strategy_2_frequency                                                 24.0
corrective_strategy_3                                      STR-I-016_ChangeChampions
corrective_strategy_3_frequency                                                 24.0
Name: 0, dtype: object

In [ ]:
# ============================================================
# PASO 40. INTERPRETACIÓN AUTOMÁTICA MEJORADA EN ESPAÑOL
# ============================================================

def translate_social_debt_level(level):
    mapping = {
        "High Social Debt": "alta deuda social",
        "Medium Social Debt": "deuda social media",
        "Low Social Debt": "baja deuda social"
    }
    return mapping.get(level, level)


def generate_issue_report(issue_number, diagnosis_df=df_final_diagnosis_clean):
    """
    Genera un reporte interpretativo en español para un issue específico.
    """

    result = diagnosis_df[
        diagnosis_df["issue_number"] == issue_number
    ]

    if result.empty:
        return f"No se encontró el issue {issue_number} en el diagnóstico final."

    row = result.iloc[0]

    level_es = translate_social_debt_level(row["social_debt_level"])

    report = f"""
El issue {issue_number} presenta un nivel de {level_es}, con un Social Debt Index de {round(row['social_debt_index'], 3)} y {int(row['comment_count'])} comentarios analizados.

El diagnóstico adaptativo indica que las principales macrocausas asociadas al issue son: {row['macrocause_1']}, {row['macrocause_2']} y {row['macrocause_3']}. Estas macrocausas sugieren que la deuda social del issue se relaciona con una combinación de factores técnicos, comunicativos y organizacionales.

A nivel de microcausas, las señales más relevantes son: {row['microcause_1']}, {row['microcause_2']} y {row['microcause_3']}. Esto permite identificar con mayor precisión los factores específicos que explican la acumulación de deuda social en el issue.

Los community smells dominantes son: {row['community_smell_1']}, {row['community_smell_2']} y {row['community_smell_3']}. Estos patrones indican posibles desconexiones entre actores, tareas, decisiones y dependencias técnicas dentro de la comunidad de desarrollo.

Los principales riesgos asociados son: {row['risk_1']}, {row['risk_2']} y {row['risk_3']}. Por tanto, el issue puede derivar en problemas de documentación, mantenimiento, compatibilidad, retrabajo o pérdida de coordinación, según las evidencias observadas.

Como estrategias preventivas, el modelo recomienda priorizar: {row['preventive_strategy_1']}, {row['preventive_strategy_2']} y {row['preventive_strategy_3']}. Estas estrategias buscan reducir la probabilidad de que las causas identificadas se repitan o se intensifiquen.

Como estrategias correctivas, el modelo recomienda considerar: {row['corrective_strategy_1']}, {row['corrective_strategy_2']} y {row['corrective_strategy_3']}. Estas acciones están orientadas a mitigar los efectos ya presentes y apoyar la recuperación del issue.

En síntesis, el issue {issue_number} evidencia una acumulación de señales sociotécnicas que justifican una intervención adaptativa. El diagnóstico integra causas, community smells, riesgos y estrategias, permitiendo pasar de una clasificación de deuda social a una recomendación accionable.
"""

    return report.strip()


# Probar con el issue más crítico
print(generate_issue_report(60423))

El issue 60423 presenta un nivel de alta deuda social, con un Social Debt Index de 1.0 y 76 comentarios analizados.

El diagnóstico adaptativo indica que las principales macrocausas asociadas al issue son: Technical complexity, compatibility, and system constraints, Communication and shared understanding breakdowns y Organizational and procedural workflow constraints. Estas macrocausas sugieren que la deuda social del issue se relaciona con una combinación de factores técnicos, comunicativos y organizacionales.

A nivel de microcausas, las señales más relevantes son: Compatibility Constraints, System configuration constraints y Technical complexity due to dependencies. Esto permite identificar con mayor precisión los factores específicos que explican la acumulación de deuda social en el issue.

Los community smells dominantes son: Missing Link, Socio-Technical Congruence Gap y Power Distance. Estos patrones indican posibles desconexiones entre actores, tareas, decisiones y dependencias técnicas dentro de la comunidad de desarrollo.

Los principales riesgos asociados son: RSK-005_Documentation_Gaps_Risk, RSK-013_TechnicalMaintenanceRisk y RSK-021_BackwardCompatibilityRisk. Por tanto, el issue puede derivar en problemas de documentación, mantenimiento, compatibilidad, retrabajo o pérdida de coordinación, según las evidencias observadas.

Como estrategias preventivas, el modelo recomienda priorizar: PS-026_CompatibilityManagement, PS-027_TechnicalDocumentationPractices y PS-004_InterfaceClarificationWorkshops. Estas estrategias buscan reducir la probabilidad de que las causas identificadas se repitan o se intensifiquen.

Como estrategias correctivas, el modelo recomienda considerar: CS-034_ResourceUseCorrection, STR-I-015_ChangeManagementTraining y STR-I-016_ChangeChampions. Estas acciones están orientadas a mitigar los efectos ya presentes y apoyar la recuperación del issue.

En síntesis, el issue 60423 evidencia una acumulación de señales sociotécnicas que justifican una intervención adaptativa. El diagnóstico integra causas, community smells, riesgos y estrategias, permitiendo pasar de una clasificación de deuda social a una recomendación accionable.

In [ ]:
# ============================================================
# PASO 39. GENERAR INTERPRETACIÓN AUTOMÁTICA DEL DIAGNÓSTICO
# ============================================================

def generate_issue_interpretation(issue_number, diagnosis_df=df_final_diagnosis_clean):
    """
    Genera una interpretación textual automática del diagnóstico adaptativo.
    """

    result = diagnosis_df[
        diagnosis_df["issue_number"] == issue_number
    ]

    if result.empty:
        return f"No se encontró el issue {issue_number} en el diagnóstico final."

    row = result.iloc[0]

    text = f"""
El issue {issue_number} presenta un nivel de {row['social_debt_level']} con un Social Debt Index de {round(row['social_debt_index'], 3)} y {int(row['comment_count'])} comentarios analizados.

El diagnóstico indica que las principales macrocausas asociadas al issue son:
1) {row['macrocause_1']},
2) {row['macrocause_2']}, y
3) {row['macrocause_3']}.

A nivel de microcausas, las señales más fuertes son:
1) {row['microcause_1']},
2) {row['microcause_2']}, y
3) {row['microcause_3']}.

Los community smells dominantes son:
1) {row['community_smell_1']},
2) {row['community_smell_2']}, y
3) {row['community_smell_3']}.

Los principales riesgos asociados son:
1) {row['risk_1']},
2) {row['risk_2']}, y
3) {row['risk_3']}.

Como estrategias preventivas, el modelo recomienda priorizar:
1) {row['preventive_strategy_1']},
2) {row['preventive_strategy_2']}, y
3) {row['preventive_strategy_3']}.

Como estrategias correctivas, el modelo recomienda considerar:
1) {row['corrective_strategy_1']},
2) {row['corrective_strategy_2']}, y
3) {row['corrective_strategy_3']}.

En síntesis, este issue refleja una acumulación de deuda social asociada con problemas sociotécnicos recurrentes, donde las causas, smells, riesgos y estrategias sugieren la necesidad de intervención adaptativa tanto preventiva como correctiva.
"""

    return text.strip()


# Probar con el issue más crítico
print(generate_issue_interpretation(60423))

El issue 60423 presenta un nivel de High Social Debt con un Social Debt Index de 1.0 y 76 comentarios analizados.

El diagnóstico indica que las principales macrocausas asociadas al issue son:
1) Technical complexity, compatibility, and system constraints,
2) Communication and shared understanding breakdowns, y
3) Organizational and procedural workflow constraints.

A nivel de microcausas, las señales más fuertes son:
1) Compatibility Constraints,
2) System configuration constraints, y
3) Technical complexity due to dependencies.

Los community smells dominantes son:
1) Missing Link,
2) Socio-Technical Congruence Gap, y
3) Power Distance.

Los principales riesgos asociados son:
1) RSK-005_Documentation_Gaps_Risk,
2) RSK-013_TechnicalMaintenanceRisk, y
3) RSK-021_BackwardCompatibilityRisk.

Como estrategias preventivas, el modelo recomienda priorizar:
1) PS-026_CompatibilityManagement,
2) PS-027_TechnicalDocumentationPractices, y
3) PS-004_InterfaceClarificationWorkshops.

Como estrategias correctivas, el modelo recomienda considerar:
1) CS-034_ResourceUseCorrection,
2) STR-I-015_ChangeManagementTraining, y
3) STR-I-016_ChangeChampions.

En síntesis, este issue refleja una acumulación de deuda social asociada con problemas sociotécnicos recurrentes, donde las causas, smells, riesgos y estrategias sugieren la necesidad de intervención adaptativa tanto preventiva como correctiva.

In [ ]:
# ============================================================
# PASO 41. GENERAR REPORTE AUTOMÁTICO PARA TODOS LOS ISSUES
# ============================================================

df_final_diagnosis_clean["adaptive_diagnosis_report"] = (
    df_final_diagnosis_clean["issue_number"]
    .apply(lambda issue: generate_issue_report(issue))
)

display(
    df_final_diagnosis_clean[
        [
            "issue_number",
            "social_debt_index",
            "social_debt_level",
            "adaptive_diagnosis_report"
        ]
    ].head(10)
)

print("Dimensiones con reporte textual:", df_final_diagnosis_clean.shape)

,issue_number,social_debt_index,social_debt_level,adaptive_diagnosis_report
0,60423,1.000000,High Social Debt,El issue 60423 presenta un nivel de alta deuda...
1,59364,0.729301,High Social Debt,El issue 59364 presenta un nivel de alta deuda...
2,134737,0.706681,High Social Debt,El issue 134737 presenta un nivel de alta deud...
3,18266,0.648390,High Social Debt,El issue 18266 presenta un nivel de alta deuda...
4,59699,0.622471,High Social Debt,El issue 59699 presenta un nivel de alta deuda...
5,19643,0.618452,High Social Debt,El issue 19643 presenta un nivel de alta deuda...
6,134251,0.597035,High Social Debt,El issue 134251 presenta un nivel de alta deud...
7,18408,0.539703,High Social Debt,El issue 18408 presenta un nivel de alta deuda...
8,18450,0.539299,High Social Debt,El issue 18450 presenta un nivel de alta deuda...
9,18158,0.528994,High Social Debt,El issue 18158 presenta un nivel de alta deuda...

Dimensiones con reporte textual: (265, 41)

In [ ]:
# ============================================================
# PASO 42. EXPORTAR DIAGNÓSTICO FINAL CON REPORTE TEXTUAL
# ============================================================

output_final_report = "adaptive_social_debt_diagnosis_final_with_report.xlsx"

df_final_diagnosis_clean.to_excel(output_final_report, index=False)

print("Archivo exportado:", output_final_report)
print("Dimensiones:", df_final_diagnosis_clean.shape)

Archivo exportado: adaptive_social_debt_diagnosis_final_with_report.xlsx
Dimensiones: (265, 41)